### ISSUE TITLE
[Bug]: babelfishpg_tsql extension does not build with parallel make

### ISSUE THREAD

**Issue by wieck** [babelfish-for-postgresql/babelfish_extensions#100]
### Contact Details

jan@wi3ck.info

### What happened?

When building as `make -j16 -C contrib all` (on an actual 16-core VM) building of the *babelfishpg_tsql* extension fails with
```
src/backend/utils/mb/conversion_procs/utf8_and_sjis/utf8_and_sjis.c:17:10: fatal error: src/backend/utils/mb/Unicode/sjis_to_utf8.map: No such file or directory
 #include "src/backend/utils/mb/Unicode/sjis_to_utf8.map"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: src/backend/utils/mb/conversion_procs/utf8_and_sjis/utf8_and_sjis.o] Error 1
```
There seem to be dependencies missing in the *cmake* generated Makefiles.

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Fedora

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kuntalghosh** [comment]
You need to export both PG_CONFIG and PG_SRC before executing the make command.
