### ISSUE TITLE
[Question]: Batch create view syntax error

### ISSUE THREAD

**Issue by williamgosse** [babelfish-for-postgresql/babelfish_extensions#105]
### Contact Details

bgosse@aresprism.com

### What's the question?

Can someone explain this error I'm seeing:
# Input file: C:\dev\babelfish_compass-main\..\temp\scripts\E_CreateViews.sql. This file generated at 25-Mar-2022 10:39:47

Syntax error in batch 1, starting at line 1 in file C:\dev\babelfish_compass-main\..\temp\scripts\E_CreateViews.sql
Batch=[	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VWONLINEUSERS') BEGIN
	DROP VIEW [VWONLINEUSERS]
	END;

The sql file I'm analyzing has about 200 of these if statements followed by about 200 create view statements.  When I run this with babelfish all the if statements work fine but when I hit the first create view statement I get a non-descript syntax error. The weird thing I can pretty much run each create view separately with no error and successfully create the view.

I be so grateful if someone can explain what's going on. I'm assuming there is some relationship between the babelfish compass error I'm seeing above and the babelfish syntax error I get when I run the the sql file sqlcmd. Here's the syntax error:
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 222
syntax error near 'VIEW' at line 222 and character position 7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by williamgosse** [comment]
One other point: I'm running babelfish 1.10 with AWS Aurora Postgres 13.5.

**Comment by robverschoor** [comment]
The SQL above is valid and works without error in all Babelfish versions - I cannot reproduce the error you quoted. But there seems to be a bigger picture as your error message mentions "line 222" ? 
Also, the Compass error is not clear to me (which Compass version?)
I guess we need to see the full input file.  You can email me directly at rcv@amazon.com if you don't want to post it here.

**Comment by williamgosse** [comment]
Thanks for your response. I was able get around by adding the GO command after each CREATE VIEW statement in my SQL file.

**Comment by robverschoor** [comment]
my guess: the problem is that CREATE VIEW must be the first (and only statement in the batch -- and it wasn't. Makes sense?

**Comment by suprio-amzn** [comment]
@williamgosse: Was the issue you were facing fully resolved now? Do you need additional help on this one?
