### ISSUE TITLE
[Question]: Tables created in postgresql are not visible when using sqlserver client connections.

### ISSUE THREAD

**Issue by weiya1990** [babelfish-for-postgresql/babelfish_extensions#108]
### Contact Details

1830624909@qq.com

### What's the question?

Table created using Postgres JDBC, I want MSSQL JDBC to read into this table. How do I operate?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
Babelfish performs a mapping of schema names as described in https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish.html#babelfish-architecture , so the schema names may be different when seen from T-SQL vs. from PG SQL.

**Comment by max-webster** [comment]
See also https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/79 for some details about containment and visibility of the Babelfish-owned objects. MSSQL JDBC can't "see" outside of the Babelfish container database. 

Creating Postgres objects inside the Babelfish container database doesn't set up all the same metadata as when those objects are created via T-SQL in Babelfish. So currently there isn't full interoperability by using Postgres to create things inside the Babelfish database.

**Comment by max-webster** [comment]
This is all the info or recommendations that are available at the moment. So I'll close this issue now.
