### ISSUE TITLE
[Question]: Can I see my SQL Server database in AWS Aurora Postgres?

### ISSUE THREAD

**Issue by williamgosse** [babelfish-for-postgresql/babelfish_extensions#112]
### Contact Details

bgosse@aresprism.com

### What's the question?

I have a question!  I was able to create a database using the SQL Server Management Studio via babelfish in AWS Aurora Postgres. I tried to view that database in AWS Aurora Postgres via a postgres client (HeidiSQL) using 5432 port.  I can connect fine but can't see my database. Is what I'm doing even possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
From a babelfish perspective, there are not PG databases at all. All babelfish activity happens inside one specific PG container database created for this purpose. In Aurora, it's named babelfish_db; when using the opensource code, you can pick any name. 
When connecting to the TDS port (1433), the session is placed inside this PG container database, and cannot connect anywhere else.  Inside this container  database, Babelfish emulates the SQL Server multi-DB experience: you can run sp_helpdb, query sysdatabases, change the DB context with "USE dbname" , etc. 
When you run CREATE DATABASE in T-SQL, this creates a set of schemas in the PG database. Babelfish presents these as if it is a T-SQL database. From a PG perspective, you will see the schemas that are created. See the documentation for further details.

**Comment by williamgosse** [comment]
Thanks, that was was an awesome explanation.

**Comment by suprio-amzn** [comment]
The docs explaining the above are [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish.html#babelfish-architecture).
