### ISSUE TITLE
[Bug]: Index on binary column doesn't seem to be used

### ISSUE THREAD

**Issue by egnwd** [babelfish-for-postgresql/babelfish_extensions#1136]
### What happened?

We have a table with an index on a binary column of our table. We noticed performance issues when querying using that column, the plan from babelfish shows a seq scan, instead of using the index.
We've attempted to rebuild the index with no luck. Other indexes we have on non-binary columns seem to work just fine (and other binary-column-based indexes have this issue). I couldn't see anything in the documentation to show that this is unsupported but I might have missed something.

I can see that query hints are unsupported so cannot try that, curious if there are any known workarounds for this?

Babelfish version: (dropdown below not working)
```
Babelfish for Aurora Postgres with SQL Server Compatibility - 12.0.2000.8
Nov 29 2022 05:28:01
Copyright (c) Amazon Web Services
PostgreSQL 14.3 on aarch64-unknown-linux-gnu
```

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Amazon Linux

### Relevant log output

```shell
Query Text: SELECT * FROM Content WHERE Hash = 0xA99646C309997AC395216454A2E68238638D8BC66A2E57E9A1192AAD8AD90C29
Seq Scan on content  (cost=0.00..928554.28 rows=10718051 width=243)
  Filter: ((hash)::bbf_varbinary = '0xa99646c309997ac395216454a2e68238638d8bc66a2e57e9a1192aad8ad90c29'::bbf_varbinary)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by egnwd** [comment]
Just an update: I saw that there was a new engine version with some query hint updates for index hints, tried on that version to no avail.

```
Babelfish for Aurora PostgreSQL with SQL Server Compatibility - 12.0.2000.8
Jan  7 2023 00:13:43
Copyright (c) Amazon Web Services
PostgreSQL 14.6 on aarch64-unknown-linux-gnu (Babelfish 2.3.0)
```

**Comment by robverschoor** [comment]
In a quick try in v.2.2.0 and 2.3.0, I am seeing an index on a varbinary column being used as expected (without using hints) so there does not seem to be a fundamental issue around the feature. That leaves the usual suspects: updated statistics (ANALYZE) and selectivity of the values in the column.
If you feel none of that explains it, please post a full reproduction,

**Comment by egnwd** [comment]
Firstly, thank you for the speedy response.
After trying the ANALYZE to update the statistics I see no change.

I've created a small table from the table that's having an issue.

### Table Creation 
Create Script (generated from SSMS)
```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Example] (
        [Id] [bigint] IDENTITY(1,1) NOT NULL,
        [Hash] [binary](32) NOT NULL,
        [Content] [varbinary](max) NULL,
        [ContentLocation] [varchar](max) NULL,
 CONSTRAINT [PK_Example] PRIMARY KEY CLUSTERED
(
        [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Example_Hash] UNIQUE NONCLUSTERED
(
        [Hash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

### Seed data
I then copy just the first 100 rows from the table having the issue, the data is all of the form below:

Id: identity bigint column
Hash: BINARY(32) column
Content: all NULL in this DB
ContentLocation: varchar(MAX) of the form 's3://bucket/location/<hexstring of the hash>'

```sql
INSERT INTO Example (Hash, Content, ContentLocation)
SELECT Hash, Content, ContentLocation FROM OtherTable
WHERE OtherTable.Id BETWEEN 0 AND 100;
GO
```

This seems to have been enough to reproduce the issue.

### Query plan:

Also, unsure if it's related but if I try a query plan off the bat after connecting to the DB I get an error, but if I run the same query once the error goes away (example below)

```
1> SET BABELFISH_SHOWPLAN_ALL ON;
2> GO
1> SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D;
2> GO
Msg 33557097, Level 16, State 1, Server mydb-1, Line 1
Type VARBINARY is not supported for input 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D.
1> SET BABELFISH_SHOWPLAN_ALL OFF;
2> GO
1> SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D;
2> GO
Id                   Hash                                                               Content ContentLocation
-------------------- ------------------------------------------------------------------ ------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                   5 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D NULL    s3://bucket/datalocation/88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D

(1 rows affected)
1> SET BABELFISH_SHOWPLAN_ALL ON;
2> GO
1> SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D;
2> GO
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Query Text: SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D
Seq Scan on example  (cost=0.00..4.20 rows=48 width=235)
  Filter: ((hash)::bbf_varbinary = '0x88c452ff8a8f08a4235d59cc041d63fdefe6c23fa7631da5c92ebc1bd8fe1d5d'::bbf_varbinary)
```

**Comment by robverschoor** [comment]
Thanks. Would you mind making the data rows available as well, by BCP?
I.e. `bcp yourdb..Example out Example.bcp -c -S... -U... -P...` , and share the produced file (if you don;t want to attach it here, you can email it to rcv@amazon.com). If there's anything confidential in the column, please wipe that out first -- but it doesn't look like that would be the case.

**Comment by egnwd** [comment]
Cheers, I've done that and sent it to your email!

**Comment by robverschoor** [comment]
Thanks for sharing the reproduction.
What is happening is that your table with 95 rows is considered too small to use an index efficiently. When I add another 1000 rows, it is using indeed using the index. This is not uncommon to see happen on small tables for a cost-based query optimizer. It may be that SQL Server uses the index also on a small table, but this is where the PG query processing internals may end up differently.  Overall, I don't think there is anything wrong here.

**Comment by egnwd** [comment]
Hmmm, interesting. I've tried adding another 1000 & 2000 to the example I shared and the plan still shows a Seq Scan. The source table from which I produced the example 95 rows is 21million rows, so certainly large enough I would hope.

Thank you for the investigation so far. If there is nothing you believe is wrong should I close out the issue?

**Comment by robverschoor** [comment]
Here's what I did after creating the table and loading your 95 rows (the formatting seems a bit off but you'll get the idea):

```
1> insert example(hash, content, ContentLocation) select newid(), null, null from generate_series(1,1000) -- using PG-leaked function for convenience
2> go

(1000 rows affected)

1> SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D;
2> GO
Id                   Hash                                                               Content ContentLocation
                   5 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D NULL    s3://bucket/location/88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D

(1 rows affected)

1> SET BABELFISH_SHOWPLAN_ALL ON;
2> GO
1> SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D;
2> GO
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------
Query Text: SELECT * FROM Example WHERE Hash = 0x88C452FF8A8F08A4235D59CC041D63FDEFE6C23FA7631DA5C92EBC1BD8FE1D5D
Bitmap Heap Scan on example  (cost=4.42..21.27 rows=548 width=144)
  Recheck Cond: ((hash)::bbf_varbinary = '0x88c452ff8a8f08a4235d59cc041d63fdefe6c23fa7631da5c92ebc1bd8fe1d5d'::bbf_varbinary)
  ->  Bitmap Index Scan on ix_example_hashexample33daac9812368d0ece1031b890da5e0a  (cost=0.00..4.29 rows=548 width=0)
        Index Cond: ((hash)::bbf_varbinary = '0x88c452ff8a8f08a4235d59cc041d63fdefe6c23fa7631da5c92ebc1bd8fe1d5d'::bbf_varbinary)

1> SET BABELFISH_SHOWPLAN_ALL OFF
2> go
```

**Comment by suprio-amzn** [comment]
@egnwd: I see that you are running on AWS. Could you open a support ticket with AWS so that we can look at your environment to determine if this is an issue with how Babelfish for Aurora is being used?

**Comment by egnwd** [comment]
@rcv-aws Thank you for your response, while it's not what I'm seeing it's good to know this is at least possible for our usecase!

@suprio-amzn I can look at doing that this early this week.

**Comment by egnwd** [comment]
Opened with AWS, I'll update this issue if we manage to find a resolution.

**Comment by forestkeeper** [comment]
I have a solution work out can help use index for varbinary 

If you have opened the AWS instance, I can make the change for you

**Comment by suprio-amzn** [comment]
@egnwd : A fix to this issue should be available in the next release and has been checked in with this commit (https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/94f8280d38132a47c6f6e8fd00922dbe9279f3f1).

**Comment by egnwd** [comment]
@suprio-amzn Excellent thank you! Do you know when that release is expected to be available?

**Comment by suprio-amzn** [comment]
@egnwd: The Babelfish for Aurora PostgreSQL releases are available on AWS now.
