### ISSUE TITLE
[Bug]: Using "left join" returns an error

### ISSUE THREAD

**Issue by NazarkinDmitry** [babelfish-for-postgresql/babelfish_extensions#115]
### What happened?

Hi.
There is an error when executing a query with linking tables.

Creating tables:

> CREATE TABLE table1(
> 	id int,		
> 	Comment nvarchar(20),
> PRIMARY KEY CLUSTERED 
> (
> 	id ASC
> )WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
> ) ON [PRIMARY]
> 
> CREATE TABLE table2(
> 	id int,	
> 	table1_id int,
> 	Comment nvarchar(20),
> PRIMARY KEY CLUSTERED 
> (
> 	id ASC
> )WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
> ) ON [PRIMARY]

Insert the data in the table1:

> INSERT INTO table1(id, Comment)
> VALUES(1, 'test 1'),
> (2, 'test 2'),
> (3, 'test 3'),
> (4, 'test 4'),
> (5, 'test 5')

Executing the query :

> select
>   *
> from table1 a
> left join table2 b on b.table1_id = a.id

_Query returns an error._ 

If you make such a query, then there will be no error:

> select
> *
> from table2 b
> left join table1 a on a.id = b.table1_id

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
This seems to be a bug indeed. Thanks for catching that. We'll look into it.

**Comment by marcocram82** [comment]
This error occurs when the secondary table column used in the join is not null, if it's nullable no error occurs

**Comment by NazarkinDmitry** [comment]
Hello,  any news? :)

**Comment by robverschoor** [comment]
This has been fixed both in Babelfish v.1.3.0 and v.2.1.0. Both have been released for Aurora. I am not sure how far the OSS currently is for those releases, but if it's not ready, it'll be close.

**Comment by marcocram82** [comment]
thanks

> This has been fixed both in Babelfish v.1.3.0 and v.2.1.0. Both have been released for Aurora. I am not sure how far the OSS currently is for those releases, but if it's not ready, it'll be close.
