### ISSUE TITLE
[Bug]: Sqlcmd fails with communication link failure

### ISSUE THREAD

**Issue by congoamz** [babelfish-for-postgresql/babelfish_extensions#12]
### What Happened

- When following the instructions in contrib/README.md, at the last step, sqlcmd cannot properly connect to the Babelfish database (see console output below). This problem can be fixed by following an older version of the Postgres script than what is provided in the instructions. I will create a PR to update the docs with this older version
```
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x68.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Communication link failure.
```
### Version

- BABEL_1_X_DEV

### OS

- Amazon Linux 2

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nasbyj** [comment]
Fixed by PR #13
