### ISSUE TITLE
installing Babelfish Compass in an enterprise envrionment

### ISSUE THREAD

**Issue by JeffSmithUSDA** [babelfish-for-postgresql/babelfish_extensions#126]
### Contact Details

jeffreyd.smith@usda.gov

### What's the question?

For Windows, I need to be able to install BabelFish Compass to a path that includes spaces in the path (i.e. C:\Program Files\BabelFish).  Because of security policy in our environment, it is generally difficult to put apps in other places and for regular users (non admins) to be able to run them.  As your batch file is currently designed, the space in "C:\Program Files" causes the batch file not to work.  If I put it in a folder path that doesn't contain a space, then it works.  But we are not allowed to put it in a different folder other than C:\Program Files\ or C:\Program Files (x86).  I tried putting it in C:\Programdata\, but policy zaps it there as well.

Do you have a version of the batch file which will work where the path installed is C:\Program Files or C:\Program Files (x86)?

Thanks,  - Jeff Smith
Integration 
USDA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
It should work on sch a path if you edit line 16 the .bat file and add double quotes around the right-hand side. 
I.e.:
`SET COMPASS="%cd%"`

Otherwise, good point. Will incorporate this.

**Comment by robverschoor** [comment]
Incidentally, this issue should have been placed in https://github.com/babelfish-for-postgresql/babelfish_compass/issues

**Comment by JeffSmithUSDA** [comment]
Thanks Rob, I appreciate the help.  I figured there was a separate path for compass, but from where I was on the babelfish page, I couldn't figure out how to find it and get there.  My apologies.  Again, thanks for the help, much appreciated.
