### ISSUE TITLE
[Bug]:  BABEL_3_1_STABLE babelfish_extensions/contrib/babelfishpg_tds to be unable to build

### ISSUE THREAD

**Issue by zekiguven** [babelfish-for-postgresql/babelfish_extensions#1401]
### What happened?

When I execute (BABEL_3_1_STABLE) make on ubuntu 20.04, the compilation reports an error. 

```
 cd ${PG_SRC}/contrib/babelfishpg_tsql
 make -j ${JOBS}
```

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tds

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Relevant log output

```shell
In file included from src/linked_servers.c:11:
src/linked_servers.h:2:10: fatal error: sybdb.h: No such file or directory
    2 | #include "sybdb.h"
      |          ^~~~~~~~~
compilation terminated.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by suprio-amzn** [comment]
@zekiguven: Is this now fixed with the commit (https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/282faa20eb88cbd6c2d8d7264a1b9655fbb4c982)?

**Comment by zekiguven** [comment]
Yes fixed, thank you.
