### ISSUE TITLE
[Question]: BABEL_2_X_DEV latest commit cannot compile babelfish_tsql

### ISSUE THREAD

**Issue by zxwsbg** [babelfish-for-postgresql/babelfish_extensions#142]
### Contact Details

zxwsbg@qq.com

### What's the question?

Pg kernel version is 14.2, I meet this error . I have built and install antlr4.

src/multidb.c: In function 'get_physical_schema_name':
src/multidb.c:879:2: warning: '__builtin_strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  879 |  strncpy(name, schema_name, strlen(schema_name));
      |  ^~~~~~~
src/multidb.c:879:2: note: length computed here
src/pl_comp-2.o:(.bss+0x0): multiple definition of `pltsql_curr_compile_body_lineno'
src/pl_comp.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make: *** [babelfishpg_tsql.so] Error 1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by zxwsbg** [comment]
I built it with GCC 10.3.0 , in GCC 7.3 this problem doesn't appear.

**Comment by zxwsbg** [comment]
<img width="2047" alt="wecom-temp-da4266e0dad6d9fc7a8b1c03c1ea07d4" src="https://user-images.githubusercontent.com/31441847/172380450-f3d9332a-f9a2-49b7-9ff3-2ff06600581d.png">
https://gcc.gnu.org/gcc-10/changes.html 
gcc 10 change the default linking option.
So need add PG_CFLAGS += -fcommon in Makefile

**Comment by 3manuek** [comment]
Hi @zxwsbg ,

I have tested the compilation using `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` and it works properly. I didn't reproduce this yet on a higher version, but we'll surely test this.

**Comment by suprio-amzn** [comment]
@zxwsbg: Is this still an issue?
