### ISSUE TITLE
[Question]: What is the recommended method of running SSIS jobs on Babelfish using Postgres Aurora?

### ISSUE THREAD

**Issue by wallo-zz** [babelfish-for-postgresql/babelfish_extensions#1546]
### Contact Details
Walewein Noordam, waleweinnoordam@gmail.com

### What's your question?
Please let me know if this is not the correct channel for this a question and also where I can ask this instead.

At the present I'm working on migrating two SQL Server database clusters from private cloud to AWS. One main reason for doing this migration is to be able to change the database engine to Postgresql, but the effort is too big to do it all at once. Therefore we are currently looking at Babelfish to be able to migrate these workloads while keeping the migration itself to a limited scope. A large portion of the current codebase is being handled by running SSIS jobs that trigger stored procedures and contain other business logic.

Now I've been assessing the Babelfish tool and there seems to be decent compatibility between the existing codebase and the target, but I have not been able to find any documentation or recommendations regarding the usage of SSIS jobs on Babelfish using Postgres Aurora. It is my intention to keep running the SSIS jobs while they are connected to the migrated codebase that is running on Babelfish and after the migration has been completed to start moving towards another AWS service e.g. AWS Glue. My question to the maintainers is, what is the recommended method of running SSIS jobs on Babelfish and do you have any reference documentation that I can use for migrating and running these jobs?

If you require any other information, please let me know!

### Version
Haven't chosen a version yet, most likely it will be newest released version that's is available for use with AWS DMS.

### Code of Conduct
- [x] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
This is just out: https://aws.amazon.com/blogs/database/automate-the-migration-of-microsoft-ssis-packages-to-aws-glue-with-aws-sct/
This will work together with Babelfish.

**Comment by suprio-amzn** [comment]
@wallo-zz: Hopefully the above blog gives you enough information. If you need additional assistance please open a case with AWS Support who can put you in touch with other solution architects who can help with the above integration scenario.

**Comment by wallo-zz** [comment]
Thanks for getting back on this topic. The link @robverschoor mentions is very interesting for migrating the SSIS packages to Glue. But before we do so, it is important to have the database itself migrated and running with as little changes to SSIS as possible. I've checked some other sources as well and was able to find the following source: https://aws.amazon.com/blogs/database/modify-ssis-packages-from-sql-server-to-babelfish-for-aurora-postgresql/

This article suggests to run an EC2 instance with SQL Server and run the SSIS from there. Then you can connect to your Postgres with Babelfish enabled database using the connection manager.

I've been into contact with a few solution architects from AWS, and they agree this is a good solution as well. So for now, we can close this issue unless someone else has something to add to this discussion.
