### ISSUE TITLE
[Bug]: Incorrect column name when column is enclosed in parens

### ISSUE THREAD

**Issue by staticlibs** [babelfish-for-postgresql/babelfish_extensions#1567]
### What happened?

When column is enclosed in parens (round brackets) and no alias is specified, then the column name in result set is returned incorrectly:

```
create table tab1(val1 int);
insert into tab1 values(42);
select (val1) from tab1;
+------+
| (val |
+------+
| 42   |
+------+
```

In real code bases this can happen with this use of `distinct` (that [is misleading](https://stackoverflow.com/a/31679169), but still not infrequent):

```
select distinct(val1) from tab1;
+------+
| (val |
+------+
| 42   |
+------+
```

I have a fix that seems to work, will create a PR shortly.

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Fedora

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
Does your fix work for an arbitrary number of brackets, i.e. SELECT ((((val)))) FROM tab1 ?
Ibid. for SELECT DISTINCT((((val))))

**Comment by staticlibs** [comment]
@rcv-aws , yes multiple levels of brackets are handled, these are all the scenarios I've checked to work correctly with the patch - [select-clause-parens.sql](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/360152e8892a705b2a048cf16336a2875c6d221f/test/JDBC/input/select-clause-parens.sql).

**Comment by staticlibs** [comment]
Commit [c549c79](https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/c549c794f174b3a95588b02bfd4efdfabda3d82a) was pushed recently, that fixes the problem in its simple form. But it does not cover all the cases, for example:

```
create table select_strip_parens_t1(field1 int, " field2  " int, [  field3 ] int);
go

insert into select_strip_parens_t1(field1, " field2  ", [  field3 ]) values(41, 42, 43);
go

create view select_strip_parens_v1 as
select (
  ( field1 )
), (
  ( " field2  " )
), (
  ( [  field3 ] )
)
from select_strip_parens_t1;
go
```

Creation of the view fails with:
```
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 1
column "
" specified more than once
```

See full set of tests in [this commit](https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/f1bc43b3e1544892f6e7dfae4eda587755dd02c0) prepared for (now outdated) PR #1568 .

**Comment by staticlibs** [comment]
It seems that whitespace handling was a problem after `c549c79`, updated #1568 with a fix to whitespaces in `pre_transform_target_entry` hook.

**Comment by staticlibs** [comment]
#1568 was merged, closing the issue.
