### ISSUE TITLE
[Bug]: Losing subsecond prevision on datetime inserts

### ISSUE THREAD

**Issue by calmitchell617** [babelfish-for-postgresql/babelfish_extensions#1577]
### What happened?

Babelfish is losing some subsecond precision when trying to insert a `datetime` value.

Example:

```
create table mytable(mydatetime datetime);

insert into mytable values (convert(datetime, '2019-07-24 01:01:26.183', 121));

select * from mytable;
```

The select at the end returns `2019-07-24 01:01:26.180`, which is missing the `3` at the end.

This seems to be an issue with the `datetime` column type. Making the following changes has the following results:

- Changing the column type to `datetime2` fixes the issue.
- Changing the type in the `convert` statement to `datetime2` does not fix the issue.
- Changing the type in both the column and `convert` statement to `datetime2` fixes the issue.

Sorry, this is on a client RDS instance and I do not have console access to find the Babelfish version being used at this time. I will message them to get that info, if that becomes relevant.

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
This is a known issue, the fix is in our backlog. The 3-millisecond resolution of DATETIME is implemented in Babelfish but in some cases this is not handled properly.
In any case, changing the datatype to DATETIME2 would not be a generally usable solution as it can have side effects, for example, the numeric representation of datetime which many customer apps use, only works with [SMALL]DATETIME and will produce an error with DATETIME2.

**Comment by calmitchell617** [comment]
Ok, thank you for the fast response, Rob.

Are you aware of any good workarounds for this issue, other than accepting the degraded precision?

This is for a migration of existing database(s) for a third party. The client may be OK with the lost precision but it would be nice to present an alternative, if migrating to 'datetime2' isn't an option for them, due to the reasons you mentioned.

**Comment by robverschoor** [comment]
For a specific application, changing to DATETIME2 might be a solution. If you have representative code and workload then you should find out when there are any operations that wouldn't work with DATETIME2. 
I don't see any options other than (i) accept the current milliseconds and (ii) change to DATETIME2. We will just have to fix the bug.

**Comment by robverschoor** [comment]
This issue is fixed by this PR: https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/1686. It should be included in the next release of Babelfish.

**Comment by calmitchell617** [comment]
Thank you Rob! Feel free to close this.
