### ISSUE TITLE
Elegant way of transferring timestamps?

### ISSUE THREAD

**Issue by calmitchell617** [babelfish-for-postgresql/babelfish_extensions#1579]
If a Github issue is not the right place to ask this kind of question, please let me know.

Is anyone aware of an elegant way of loading `timestamp` data types into Babelfish? For example, trying to insert one in the following way yields an error:

```
create table mytable (mycol timestamp);

insert into mytable values (null);
```
Error:
```
Cannot insert an explicit value into a timestamp column.
```

This is the _correct_ behaviour - SQL Server returns the same error. However, it makes transferring a table from an existing DB which makes use of the `timestamp` type difficult.

**Comment by AlexFriedmanAWS** [comment]
You're right, that's the correct behavior, and it's the same issue with loading `rowversion`/`timestamp` data between SQL Servers. Assuming the target data type has to stay `rowversion`/`timestamp`, the only way to load the data is to skip the `rowversion`/`timestamp` column during the data load, for example using a transformation in DMS (any other tool like `bcp`, Import/Export Wizard, AWS Glue will have similar functionality). This does mean that the `rowversion`/`timestamp` data in the target will have different values from the source, so if anything relies on the actual values of the column it would have to be adjusted to account for that.

**Comment by calmitchell617** [comment]
Got it, thank you. That answers my question.
