### ISSUE TITLE
[Bug]: Intermittent crash in ResetTDSConnection

### ISSUE THREAD

**Issue by staticlibs** [babelfish-for-postgresql/babelfish_extensions#1581]
### What happened?

I am observing an intermittent backend crash that happens when [ResetTDSConnection](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tds/src/backend/tds/tdsprotocol.c#L113) is requested by client application.

`ResetTDSConnection` calls [reset_session_properties](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tds/src/backend/tds/tdsprotocol.c#L144) that eventually calls [reset_cached_batch](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L3223). And the crash happens in `pltsql_free_function_memory` on [this assignment](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_funcs.c#L868) when the `func` itself is already freed.

I am unable to get a stable reproduction or reproduce it without the client app, the crash happens for me only when the client app runs under load and ODBC connection pooling is enabled (so TDS reset is called on existing connection taken from the pool).

It seems that there can be a simple workaround for the problematic assignment, will submit a PR with it shortly.

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jsudrik** [comment]
This is a good find. 

It will be good to get consistent repro (might try at this end as well). 

I see this - ".. the crash happens for me only when the client app runs under load and ODBC connection pooling is enabled (so TDS reset is called on existing connection taken from the pool)." and understand it won't be simple repro. 

Will be useful to document the steps when you see it. Repro at your end with some added tracing around the code snippets might give better insights. 

Any stack by any chance in errorlog?

**Comment by staticlibs** [comment]
Unfortunately didn't get anything close to the consistent repro. Narrowed it down to "app runs hundreds of inserts sequentially, then closes the connection, then reopens it". And it happened infrequently and never happened if number of inserts before close/reopen was less that a hundred.  A few times when I caught it under the debugger, stack trace was always coming from `ResetTDSConnection`. I suspect that the number of inserts required for repro was related to [MAX_FREE_CONTEXTS](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/a84f7cb52829e074aad052664489ee34e524cc44/src/backend/utils/mmgr/aset.c#L244) but never verified that.

I can only suggest to try to construct a reproducer coming from the PR change itself. With `--enable-debug` and `--enable-cassert` it is clear under debugger that the write goes to the memory that was just "freed". Perhaps [USE_VALGRIND](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/a84f7cb52829e074aad052664489ee34e524cc44/src/include/pg_config_manual.h#L303) can catch it, as I understand there is at least some support for `memcheck` in memory context impl, but I never got that far.

**Comment by staticlibs** [comment]
Corresponding PR was merged, closing the issue.
