### ISSUE TITLE
[Question]: can't create database

### ISSUE THREAD

**Issue by jurado75** [babelfish-for-postgresql/babelfish_extensions#1612]
### What happened?

I created a database on single-db but after I changed to multi-db  but my db stopped to work I checked and the dbo schema disappear on SQL server view then when I tried to delete I got a message like dbo schema does not exist, I decided deleted the database manually from sys.databases, when I try to create again I got a message guest already exists then I can't create this database, my question is how can solve this on where other tables I have to delete the old reference to this db

Thanks 

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
Changing the migration_mode is not supported. As per https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-architecture.html : "The migration mode is stored in the migration_mode parameter. You must not change this parameter after creating your cluster as you could lose access to all your previously created SQL objects."

If you want to use a different migration mode, you must create a new Babelfish/Aurora PG cluster. If you are not sure which migration mode is best for your situation, choose multi-db.

**Comment by robverschoor** [comment]
Another case came up at Github where someone changed migration_mode and lost access to their schemas: https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/1612
