### ISSUE TITLE
[Bug]: Convert database problems using tools like fullconvert

### ISSUE THREAD

**Issue by alexandre-henzen** [babelfish-for-postgresql/babelfish_extensions#1691]
### What happened?

I follow the development of Babelfish to use in our ERP system with our customers. However, so far I have not been able to use any tool to assist in data migration. Every tool I've tried over time has failed when trying to migrate the data. The main one that we already use in the company for other cases is www.fullConvert.com
It would be interesting to have support for some market tool to help with migrations, as the structures of the tables are often complex. Migrating the table structure using the tutorial, in an example bank, I could also notice extreme slowness in SSMS to expand the table structure in the utility. Tested in version 3.1

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by suprio-amzn** [comment]
Hi @alexandrehenzenkorp: Babelfish works with most tools that work with SQL Server. For example, you can use SQL Server's Import/Export Wizard that is part of SSDT/SSIS as well as the `bcp` utility for bulk data load. If you are using Babelfish for Aurora PostgreSQL you can also use AWS Data Migration Services (DMS). We do not qualify specific third-party tools.

But, we would be interested to know what error you are getting when you use [www.fullConvert.com](http://www.fullconvert.com/) for data migration.

Slowness of SSMS is a known issue and we will address that in a future release.

**Comment by alexandre-henzen** [comment]
Hi, 
When i try to sql server export wizard from SSMS occur this error when i try to select database on destionation
procedure sys.sp_catalogs_rowset2() does not exist (Microsoft SQL Server Native Client 11.0)

If i put the database name manualy, the error is:
procedure sys.sp_provider_types_100_rowset(smallint, smallint) does not exist (Microsoft SQL Server Native Client 11.0)

When i try to use Fullconvert, the error is:
"syntax near 'TABLOCK'" when try to copy data. To create tables structure is working fine.

**Comment by suprio-amzn** [comment]
@alexandrehenzenkorp: For the Import/Export Wizard use the .NET Provider (not the SQL Server Native Client)

**Comment by suprio-amzn** [comment]
> _When i try to use Fullconvert, the error is:
"syntax near 'TABLOCK'" when try to copy data. To create tables structure is working fine._

This seems to be caused by FullConvert trying to copy data into a table using the `TABLOCK` hint. This is typically used for bulk load operations by SQL Server tools. Babelfish has started to support hints, but the `TABLOCK` hint is currently not supported.

For the list of supported hints, please refer to: https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/wiki/Using-T%E2%80%90SQL-query-hints-to-improve-Babelfish-query-performance.

**Comment by alexandre-henzen** [comment]
Thanks for the feedback. If possible, considering fullconvert as an option for data migration would be a great option. The sql server migrator is not very efficient to work with a database with a large volume of tables and data, as is our case.
Over time I have always been following and trying to migrate our bank and so far without success. With each new version I manage to take a step further. For example, if I try to migrate to Dataexport from SSMS in our table, the error below occurs. I don't have the slightest idea how
deal with. It is not machine performance problem because it has high processing power and memory. Besides, Dataexport is slow. Fullconvert is already used for other things. It is a mature and reputable tool.


- Copying Rows (Error)
Messages
Error 0xc020844b: Data Flow Task 47: An exception has occurred during data insertion, the message returned from the provider is: Ocorreu um erro no nível de transporte durante o recebimento de resultados do servidor. (provider: TCP Provider, error: 0 - Foi forçado o cancelamento de uma conexão existente pelo host remoto.)
 (SQL Server Import and Export Wizard)
 
Error 0xc0047022: Data Flow Task 47: SSIS Error Code DTS_E_PROCESSINPUTFAILED.  The ProcessInput method on component "Destination 234 - ESTOQUE" (1246) failed with error code 0xC020844B while processing input "Destination Input" (1249). The identified component returned an error from the ProcessInput method. The error is specific to the component, but the error is fatal and will cause the Data Flow task to stop running.  There may be error messages posted before this with more information about the failure.
 (SQL Server Import and Export Wizard)

**Comment by KushaalShroff** [comment]
@alexandrehenzenkorp can you provide more details (for the error message you pasted) on the table schema, the database engine logs you see at time of the error and provide core dumps if available.
Additionally, if you are using Aurora PostgreSQL, feel free to open a support ticket and provide the material.

**Comment by alexandre-henzen** [comment]
I attached a database in bacpac format for them to analyze the error
[test.zip](https://github.com/babelfish-for-postgresql/babelfish_extensions/files/12411184/test.zip)

**Comment by Deepesh125** [comment]
@alexandrehenzenkorp When I tried to use Data export tier application, I am getting following error which is different from what you posted, 
```
TITLE: Microsoft SQL Server Management Studio
------------------------------

Could not extract package from specified database. (Microsoft.SqlServer.Dac)

------------------------------
ADDITIONAL INFORMATION:

Unable to reconnect to database: relation "sys.database_permissions" does not exist (Microsoft.Data.Tools.Schema.Sql)

------------------------------

relation "sys.database_permissions" does not exist (Microsoft SQL Server, Error: 33557097)

For help, click: https://docs.microsoft.com/sql/relational-databases/errors-events/mssqlserver-33557097-database-engine-error

------------------------------
BUTTONS:

OK
------------------------------

```

So it would be great if you can provide us the exact steps you are trying. Thanks in advance!

**Comment by alexandre-henzen** [comment]
I guess it's the data export version that shows the message differently. In my case, I used version 19.1 with sql server 2022. In any case, would this error be a babelfish problem to be solved?

**Comment by alexandre-henzen** [comment]
Hello, will anything be seen about this problem? We were unable to progress with the project due to this problem.

Regards,
Alexandre

**Comment by Deepesh125** [comment]
@alexandrehenzenkorp Can you please enable debug logs and share the logfiles here? To enable debug logs, run the following commands through postgres endpoint (connect using psql or similar clients):  
```
ALTER SYSTEM SET log_min_messages = debug3;
ALTER SYSTEM SET babelfishpg_tds.tds_debug_log_level = 3;
SELECT pg_reload_conf();
```
Please make sure that logfiles do not contain any sensitive information. And if you are AWS customer then consider opening internal ticket with us to expedite the process. Thank you!

**Comment by alexandre-henzen** [comment]
I did new tests with version 3.2 and the problem no longer occurs. We can consider this issue resolved. About fullconvert, the only thing the tool complains about now is the lack of Table Hint Tablock.
