### ISSUE TITLE
[Question]: Schema and data migration queries

### ISSUE THREAD

**Issue by peet83** [babelfish-for-postgresql/babelfish_extensions#17]
### What's the question?

 I do have SQL database with bunch of length stored procedures, Do I needs to rewrite them all to postgresql compatible syntax to start using the Babelfish ?

Also how do I will migrate the existing data to postgres, does Babelfish provides any tool for that?

Thank you,
Peet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nasbyj** [comment]
The [Compass tool](https://github.com/babelfish-for-postgresql/babelfish_compass) will give you a compatibility report for your existing database, including calling out any stored procedures that you'll need to modify to work with pl/tsql.

Babelfish itself doesn't provide any special tools for moving data. Data movement tools that work with SQL Server would likely work on Babelfish, provided that they operate at a logical level (as opposed to something like shipping binary transaction log data).
