### ISSUE TITLE
[Bug]: LEN function returns different values in BabelFish 

### ISSUE THREAD

**Issue by abner** [babelfish-for-postgresql/babelfish_extensions#18]
### What happened?

First of all, thank you for opensourcing babelfish. I agree it will help a lot of projects and companies to quickly migrate to the cloud with lower costs.

I did notice a behaviour in Babelfish and I think it could be an bug:

The function LEN in Babelfish, using the same collation in both actual MSQLServer and Babelfish, returns a different result. Its impacts in error (` value too long for type varchar...`) when trying to inserting a row that would work ok if the size of the varchar was calculated right.

## MSSQL

```sql
select LEN('°')
UNION ALL
select SERVERPROPERTY('collation')
```

returns

```txt
length|collation                   |
------+----------------------------+
     1|SQL_Latin1_General_CP1_CI_AS|  
```

### Babelfish

```sql
select LEN('°') length, SERVERPROPERTY('collation') collation
```

returns

```txt
length|collation                   |
------+----------------------------+
2     |SQL_Latin1_General_CP1_CI_AS|
```

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JimFinnerty** [comment]
That's curious. I'm getting a different result on Amazon Linux 2 using freetds as the client:

1> select LEN('°') length, DATALENGTH('°') as bytelen, SERVERPROPERTY('collation') as collation
2> go
length bytelen collation
1 2 sql_latin1_general_cp1_ci_as
(1 row affected)
1> 

Note that the length either in characters or bytes is not determined by the collation, but instead by the server encoding, which for Babelfish is UTF8.

**Comment by abner** [comment]
The length is 2 (two) in your result as well.

The problem is I have a field defined as nvarchar(1) and it fails to store the char `°` in Babelfish, but works at MSSQL.

**Comment by zli236** [comment]
It works for me on Amazon Linux 2. So maybe something related to your Ubuntu settings.

```
1> create table t2 (a nvarchar(1))
2> go
1> insert into t2 values ('°');
2> go

(1 rows affected)
1> select * from t2
2> go
a
-
°
```

**Comment by abner** [comment]
I compiled postgres using Debian bullseye using Docker.

Do you a have script or Dockerfile you would share with me so I can  test it here using amazonlinux?

Thanks in advance.

> It works for me on Amazon Linux 2. So maybe something related to your Ubuntu settings.
> 
> ```
> 1> create table t2 (a nvarchar(1))
> 2> go
> 1> insert into t2 values ('°');
> 2> go
> 
> (1 rows affected)
> 1> select * from t2
> 2> go
> a
> -
> °
> ```

**Comment by zli236** [comment]
I don't have one right now. Let me check with my colleagues on Monday.

**Comment by abner** [comment]
It was my bad. In the dockerfile I forgot to install the utf-8 locale, so the postgres server was running with ASCII encode by default.
