### ISSUE TITLE
[Question]: Getutcdate() invalid input syntax for type interval: "UTC"

### ISSUE THREAD

**Issue by SirNeato** [babelfish-for-postgresql/babelfish_extensions#192]
### What's the question?

I've been evaluating Aurora using Babelfish as an alternative to SQL Server, and during testing noticed that GETUTCDATE() was not supported? When `select getutcdate()` is executed, it produces the error message:
`Msg 33557097, Level 16, State 1, Line 1
invalid input syntax for type interval: "UTC"`
However GETDATE() works and returns a UTC timestamp. The same message and behavior is seen with other timestamp functions, such as sysdatetime/sysutcdatetime. We use GETUTCDATE all over our code and hope that this is some oddity we're able to work thru so as to not have to bulk convert timestamp operations.
According to the babelfish_compass BabelfishFeatures.cfg, SYSUTCDATETIME and GETUTCDATE are in the list of supported Built-in functions, so its strange to see them not operating as expected.

Additional Information:

- Babelfish Version: 1.2.1
- Aurora PostgreSQL (Compatible with PostgreSQL 13.6)

### Relevant log output or information

Cloudwatch logs report `Unmapped error found. Code: 117440642, Message: invalid input syntax for type interval: "UTC", File: datetime.c, Line: 3758, Context: babelfishpg_tsql` and `QUERY: SELECT CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS sys.DATETIME);`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
This will be fixed in v.2.1.0

**Comment by max-webster** [comment]
Closing this issue since the question is answered.
