### ISSUE TITLE
[Bug]: Can't create foreign key constraint

### ISSUE THREAD

**Issue by spencercw** [babelfish-for-postgresql/babelfish_extensions#20]
### Contact Details

@spencercw

### What happened?

```sql
create table a (
  id int identity primary key
);

create table b (
  id int identity primary key,
  foreign_id int not null references a
);
```

When creating table `b` I get a syntax error if I include the foreign key reference:
```
[S0001][33557097] syntax error near ')' at line 4 and character position 0
```

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spencercw** [comment]
Ah I've just realised it works if I specify the column as `foreign_id int not null references a(id)`. SQL Server apparently doesn't require the referenced column to be specified.

**Comment by 3manuek** [comment]
> Ah I've just realised it works if I specify the column as `foreign_id int not null references a(id)`. SQL Server apparently doesn't require the referenced column to be specified.

Yes @spencercw , looks like the [SQL Server DDL definition](https://docs.microsoft.com/es-es/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15) accepts the following pattern:

```sql
REFERENCES referenced_table_name [ ( ref_column ) ]
```

cc/ @gopinathpai @zli236

**Comment by robverschoor** [comment]
This appears to have been fixed in the latest codeline.
