### ISSUE TITLE
[Question]: is support SQL execution plan

### ISSUE THREAD

**Issue by dbit-xia** [babelfish-for-postgresql/babelfish_extensions#21]
### What's the question?

how can I view the SQL execution plan?  (set showplan_all is not available)
Or I can view the execution plan of pg

thankyou

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suprio-amzn** [comment]
Please review [https://babelfishpg.org/docs/usage/query_planning/](https://babelfishpg.org/docs/usage/query_planning/).
