### ISSUE TITLE
Implement sp_reset_connection system procedure for connection pooling

### ISSUE THREAD

**Issue by robverschoor** [babelfish-for-postgresql/babelfish_extensions#2136]
For connection pooling, some of the SQL Server drivers may call `sp_reset_connection` system procedure to reset the current connection. We need to implement the same in Babelfish. More information: https://www.google.com/search?q=sp_reset_connection

**Comment by tanscorpio7** [comment]
Add support for sys.sp_reset_connection stored procedure (https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/2758)
