### ISSUE TITLE
[QUESTION] Steps to create a new user with rw rights

### ISSUE THREAD

**Issue by codref** [babelfish-for-postgresql/babelfish_extensions#2144]
I'm having difficulties in creating new users with read/write permissions over a schema/database. I'm also struggling in creating a new "sa" equivalent user.  

So far, using TDS, I succeeded in creating a new login via `CREATE LOGIN qwe WITH PASSWORD = 'qweqweqwe'` and enabling the user to a specific DB through the statement `CREATE USER qwe FOR LOGIN qwe`.  
I was expecting the user to view all the schemas tables, but I was wrong.
The new user cannot view any table, the new user cannot create new tables on any schema.  

A workaround could be to GRANT privileges over the various objects, although this does not seem to fix the missing CREATE rights.  

Can you point me to some documentation/example? Thanks!

**Comment by robverschoor** [comment]
What you describe here is a regular login and ditto user, without any special roles. In SQL Server, that user would not have access to anything except the **guest** schema. Babelfish does the same.
If you wanted to create an **sa**-style login, then you have to grant server role **sysadmin** to the login. That will automatically make the login **dbo** in all databases. If you just want to create a user with their own schema, then **sysadmin** role is not needed but you can run (as **sysadmin**) `CREATE SCHEMA qwe_schema AUTHORIZATION qwe`

**Comment by codref** [comment]
Thanks! Can you confirm me that on version 3.2:

* there cannot be multiple db owners
* the `ALTER AUTHORIZATION ON SCHEMA` is not supported

My consideration is that one has to choose between creating a role and assign granular permissions to all the DB objectes, or assign the sysadmin role to the user - the schema authorization seems not very practical (unless planned in advance).  

In the newer commits I see advancements in this area, I'm looking forward to check the next release!

**Comment by robverschoor** [comment]
Both of those are indeed not currently supported. The work that you may have seen to be in progress is for GRANT/REVOKE on SCHEMA, not for ALTER AUTHORIZATION ON SCHEMA:: (but GRANT ON SCHEMA will not yet be included in the upcoming release v.3.4).
v.3.4 is expected to include ALTER AUTHORIZATION ON DATABASE:: .
