### ISSUE TITLE
[Enhancement]: Support Timestamp datatype

### ISSUE THREAD

**Issue by codeex** [babelfish-for-postgresql/babelfish_extensions#22]
### What this feature/enhancement tries to solve?

This is my feature request!
Timestamp as a version management field is very useful and versatile, hope to support it (PostgresQL has column Xmin)

### Version

babelfishpg_tsql (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
TIMESTAMP and ROWVERSION are supported as of v.1.2.0
