### ISSUE TITLE
Is there a CAST defined for timestamp with timezone to datetimeoffset

### ISSUE THREAD

**Issue by bradtx19** [babelfish-for-postgresql/babelfish_extensions#221]
### Contact Details

bthomas@paymerang.com

### What's the question?

(using pgAdmin)
I can see that there are CASTs defined for timestamp without time zone to datetime and datetimeoffset (and the reverse)
I also see that there is a CAST defined for timestamp with time zone to datetime.

Is is possible to CAST a timestamp with time zone to datetimeoffset?
Is it possible to CAST a datetimeoffset to timestamp with time zone?

Is there a valid link for this reference ?

**You will find an up-to-date list of unsupported data types and other functionality on the [Babelfish compatibility page](https://github.com/babelfish-for-postgresql/babelfish_project_website/blob/main/_internals/docs/usage/limitations-of-babelfish).**

When I run a Linq query that attempts to compare a DateTimeOffset variable to a timestamp with time zone column I get this exception:

**InnerException = {"operator does not exist: timestamp with time zone > datetimeoffset"}**

Can this be remedied by creating a CAST and an operator?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suprio-amzn** [comment]
@bradtx19 : Have you tried with the latest available version of Babelfish and see whether the problem still exists?
