### ISSUE TITLE
[Bug]: babelfishpg_common extension is not updated on BABEL_3_3_0__PG_15_4 release

### ISSUE THREAD

**Issue by codref** [babelfish-for-postgresql/babelfish_extensions#2227]
### What happened?

According to the release documentation found here https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/releases/tag/BABEL_3_3_0__PG_15_4, also the extension babelfishpg_common should be upgraded to version 3.3.0, but it is not.  

Is it correct that release 3.3.0 only upgrades `babelfishpg_tsql`?

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_common

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Relevant log output

```
babelfish_db=# \dx
                                List of installed extensions
        Name        | Version |   Schema   |                   Description                   
--------------------+---------+------------+-------------------------------------------------
 babelfishpg_common | 3.2.0   | public     | Transact SQL Datatype Support
 babelfishpg_tds    | 1.0.0   | public     | TDS protocol extension
 babelfishpg_tsql   | 3.3.0   | public     | Transact SQL compatibility
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 uuid-ossp          | 1.1     | public     | generate universally unique identifiers (UUIDs)
(5 rows)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by shardgupta** [comment]
We did not have any SQL changes from 3.2.0 to 3.3.0, so babelfishpg_common extension version was not updated.

**Comment by codref** [comment]
Thank you very much for your reply. I was confused by the release notes!
