### ISSUE TITLE
[Question]: tsql change the nullability of column

### ISSUE THREAD

**Issue by tax** [babelfish-for-postgresql/babelfish_extensions#228]
### What's the question?

When I run following statement 
```sql
ALTER TABLE  customer ALTER COLUMN  phone  NVARCHAR(20) NOT NULL;
```
I get the following error

```
Msg 33557097, Level 16, State 1, Line 1
'NOT NULL in ALTER TABLE ALTER COLUMN' is not currently supported in Babelfish
```
Which I believe is related to the documented difference of [ALTER TABLE](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-compatibility.html#babelfish-compatibility.tsql.limitations) _Supports adding or dropping a single column or constraint only._ 

I found the following information below [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/62#issuecomment-1025651386)
> Generally, performing DDL in PG and expecting this to be reflected on the T-SQL Babelfish layer, is not supported. Babelfish works the other direction: what you can access through the TDS port with T-SQL, can identically be accessed through the PG port when using the same PG user to connect as used when connecting to the TDS port. The reverse is however not necessarily true. While performing DDL through PG may in some cases be reflected in T-SQL, this will not always work. But more importantly, this is not recommended and may not be compatible with future releases of Babelfish.

Based on this information I am not sure if it is wise to alter the table via PSQL.

So my question is what would be the best strategy to update this table?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
It's simpler: as the error message says, NOT NULL is not currently supported with ALTER TABLE..ALTER COLUMN in Babelfish. NULL isn't either. If you specify ALTER TABLE ALTER COLUMN without NULL or NOT NULL, it should work. 
If you want to change the nullability of the column, currently there is no way to do that from T-SQL, and you'd have to use the workaround by going through PG. In this case, this should work and no adverse effects are expected.
The restriction which you reference is about adding/dropping/altering multiple columns in a single statement, and that does not apply here.

**Comment by tax** [comment]
Thanks Rob for your quick answer!  
_If you want to change the nullability_ yes, that is what I wanted to do. I will make the update through PG.

Updated title to better describe issue

**Comment by tax** [comment]
Can this be added to the list of unsupported features?: 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-compatibility.html#babelfish-compatibility.tsql.limitations-unsupported-list7

**Comment by robverschoor** [comment]
I'll submit a doc update

**Comment by max-webster** [comment]
Do we need to track this all the way through the doc update being published? Otherwise, I'll close the issue.

**Comment by robverschoor** [comment]
I suggest keeping this open until the doc update has been done
