### ISSUE TITLE
Typo for CMAKE_C_FLAGS?

### ISSUE THREAD

**Issue by japinli** [babelfish-for-postgresql/babelfish_extensions#2399]
Hi,

Does there is a typo for [`CMAKE_C_FLAGS`](https://github.com/babelfish-for-postgresql/babelfish_extensions/blame/b4868b3bf032b75fca31be3cdfb97cb26cdaa329/contrib/babelfishpg_tsql/antlr/CMakeLists.txt#L9)?

It might be`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -O2 -ggdb -w -Wno-deprecated")`, right?

**Comment by Deepesh125** [comment]
Hi @japinli, Thank you for reporting this. I have already raised PR to fix this -- https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/2400

**Comment by japinli** [comment]
> Hi @japinli, Thank you for reporting this. I have already raised PR to fix this -- #2400

Thanks for working on this.
