### ISSUE TITLE
[Bug]: AS clause is non-optional in some cases

### ISSUE THREAD

**Issue by JimFinnerty** [babelfish-for-postgresql/babelfish_extensions#24]
### Contact Details

jfinnert@amazon.com

### What happened?

The AS clause is non-optional in some cases, and the error message text is sometimes incorrect

Note: the errors below were not observed on Aurora PostgreSQL with Babelfish enabled.

On AL2 using the freetds client:

1> select LEN('°') length, DATALENGTH('°') bytelen, SERVERPROPERTY('collation') coll;
2> go
Msg 33557097 (severity 16, state 1) from BABELFISH Line 1:
"syntax error at or near "AS""

[ Note: this is an improper error message, since no AS clause was specified ]

1> select LEN('°') length, DATALENGTH('°') as bytelen, SERVERPROPERTY('collation') coll;
2> go
Msg 33557097 (severity 16, state 1) from BABELFISH Line 1:
"syntax error at or near "AS""

1> select LEN('°') length, DATALENGTH('°') as bytelen, SERVERPROPERTY('collation') as coll;
2> go
length bytelen coll
1 2 sql_latin1_general_cp1_ci_as
(1 row affected)
1> 

[ Apparently the AS clause is required for the 3rd target list item, but not for the 1st or 2nd ]

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Amazon Linux

### Relevant log output

```shell
shown above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dbit-xia** [comment]
It seems to be related to this special symbol, and it will also cause the result to be incorrect

>select '°°°', SERVERPROPERTY('collation') coll  
>go

coll result is empty!!

**Comment by dbit-xia** [comment]
When non-English symbols appear, the result will be wrong, as follows an additional **AS**
> select '好' a,SERVERPROPERTY('collation')  coll
> go
a              b
好AS 	Chinese_PRC_CI_AS

**Comment by dbit-xia** [comment]
I found code position: contrib/babelfishpg_tsql/src/tsqlIface.cpp 
>mutator.add(column_alias_as->start->getStartIndex(), "", "AS ");  //getStartIndex() return value is wrong

this line has problem, delete it , it is work,   
and space alias can not be translated.

**Comment by robverschoor** [comment]
I checked in the latest codeline, and this problem appears to have been solved.
