### ISSUE TITLE
How to setup babelfish_fwd

### ISSUE THREAD

**Issue by madanparedla** [babelfish-for-postgresql/babelfish_extensions#2408]
HI Suport can any one help me on how to setup babelfish_fwd in sql server to setup linked server from SQL SERVER to Babelfish

**Comment by staticlibs** [comment]
Hi, please see [this section](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/wiki/Babelfish-Linked-Servers#adding-babelfish-as-a-linked-server-from-sql-server) of Babelfish Linked Servers doc.

**Comment by madanparedla** [comment]
hello @staticlibs 
can you please provide any link to setup ODBC drivers for babelfish as i am new to linux environment and babelfish 

i am getting below error
[01000][unixODBC][Driver Manager]Can't open lib 'psqlodbcw.so' : file not found
[ISQL]ERROR: Could not SQLConnect

**Comment by staticlibs** [comment]
@madanparedla , to connect to Babelfish over ODBC from Linux you need to install Microsoft ODBC Driver 18 for SQL Server and use connection string like this:

```
DRIVER={ODBC Driver 18 for SQL Server};SERVER=127.0.0.1,1433;UID=jdbc_user;PWD=12345678;TrustServerCertificate=yes
```

Just I don't think this is needed at all for Linked Servers/FDW setup. I can confirm that Babelfish doc above is correct and linking between SQL Server and Babelfish works in both directions, and either of SQL Server and Babelfish can be on Windows or on Linux (PolyBase is required when SQL Server runs on Linux, but that is not a Babelfish limitation).

If you have more general questions about Babelfish, this bugtracker may be not the best place for that. It may be better to continue it on some medium for talks, like [Babelfish Discussions board](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/discussions). For Windows-specific questions you can use public Discord server (or other social links) from my GitHub profile.

**Comment by suprio-amzn** [comment]
@madanparedla: Did the above suggestion from @staticlibs work for you?
