### ISSUE TITLE
[Bug]: The execution order of the SELECT assignment statement is not compatible with BF and SQL Server

### ISSUE THREAD

**Issue by vccomnet** [babelfish-for-postgresql/babelfish_extensions#2454]
### What happened?

SELECT assignment statement, BF and SQL Server have different execution results

Hi, 
I found an issue while porting the SQL Server project to the Babelfish database, which is that the behavior of BF's SELECT assignment statement is different from SQL Server, as BF does not reference the latest value for assignment. The test screenshot is as follows:

![1](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/39423739/a8261589-3a1d-4889-b4fa-531adcd120b3)
![2](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/39423739/53802d57-cd4a-4718-8247-352b9a85a937)

In test case 1, @ TableName was not assigned the priority calculated @ Suffix, and the final output of @ TabelName was NULL, which should be an error.

![3](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/39423739/ad35af08-9167-4711-8715-775bf57d60c1)
![4](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/39423739/762bc3c8-6af2-40c3-adb0-77cff408aea3)

Similarly, in test case 2, the output of @ b should be 2.
The output of SQL Server is expected, but the output of BF is incorrect. The root cause should be that BF did not assign the latest variable value.

Please confirm if this is a bug, thank you.

Appendix:

TEST CASE 1:

DECLARE @ TableName nvarchar (100)
DECLARE @ Suffix nvarchar (100)

SELECT
@Suffix=CONVERT (VARCHAR (8), Getdata(), 112)
, @ TableName=@ Suffix

SELECT @ Suffix, @ TableName

TEST CASE 2:

DECLARE @ a int
DECLARE @ b int

SELECT
@a=1
, @ b=@ a+1

SELECT @ a, @ b

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
This is a known difference between Postgres/Babelfish and SQL Server. This query assumes that the assignment to the variables is performed in a particular order, i.e `@Suffix` is assigned first and `@TableName `is assigned next and will reference the value of the just-assigned `@Suffix` variable. PG does not work the same way, but instead uses the value of each variable before the start of the query. 
Solution is to split this into two assignments.

**Comment by robverschoor** [comment]
To add, the [Babelfish Compass tool](https://github.com/babelfish-for-postgresql/babelfish_compass/releases/latest) detects such SELECT statements where a dependency between variable assignments exists, and reports these in the "Review Semantics" category.
However, this particular case was not reported by the current version of Compass. However, when the next Compass version is released (coming 'very soon'), this case will also be reported (look for "Variable assignment dependency in SELECT" in the Compass report)
