### ISSUE TITLE
[Bug]: PHP ODBC Not Found

### ISSUE THREAD

**Issue by noerarief23** [babelfish-for-postgresql/babelfish_extensions#2501]
### What happened?

PHP 7.2
pdo_sqlsrv and sqlsrv already installed
![image](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/5919917/294be537-3dc8-4200-bb68-f62d86f5a1d4)
![image](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/5919917/2c5b865b-da15-459c-8afe-1789c45b3ee3)

already fine if connect to other host sqlserver, but always fail if connected to babelfish

![image](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/5919917/b06fcd53-b7fd-42bc-be7e-dca5bea7e4ba)

any app client example using PHP?

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by syuaip** [comment]
SQLSRV and PDO_SQLSRV drivers have Multiple Active Result Sets (MARS) [enabled by default](https://github.com/microsoft/msphpsql/wiki/Recommendations-for-improving-the-performance-of-PDO_SQLSRV-and-SQLSRV), while Babelfish [doesn't support MARS (Multiple Active Result Sets)](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-connect-sqlserver.html). For PHP code to connect to Babelfish using SQLSRV or PDO_SQLSRV driver, please [disable MARS](https://learn.microsoft.com/en-us/sql/connect/php/how-to-disable-multiple-active-resultsets-mars?view=sql-server-ver16) using/on the connection option. 

Sample code (SQLSRV driver):
```
$serverName = "<Babelfish server FQDN>, <Port number>";
$connectionInfo = array( "Database"=>"<Database name>", "UID"=>"<userID>", "PWD"=>"<password>","MultipleActiveResultSets"=>false);
sqlsrv_configure('WarningsReturnAsErrors',0);
$conn = sqlsrv_connect( $serverName, $connectionInfo);

```
Sample code (PDO_SQLSRV driver):
```
$serverName = "<Babelfish server FQDN>, <Port number>";
$database = "<Database name>";
$uid = "<userID>";
$pwd = "<password>";

try
{
  $conn = new PDO( "sqlsrv:server=$serverName; Database=$database; MultipleActiveResultSets=false", $uid, $pwd );
}
catch(PDOException $e)  
{
  $e->getMessage();
}

```

**Comment by noerarief23** [comment]
> SQLSRV and PDO_SQLSRV drivers have Multiple Active Result Sets (MARS) [enabled by default](https://github.com/microsoft/msphpsql/wiki/Recommendations-for-improving-the-performance-of-PDO_SQLSRV-and-SQLSRV), while Babelfish [doesn't support MARS (Multiple Active Result Sets)](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-connect-sqlserver.html). For PHP code to connect to Babelfish using SQLSRV or PDO_SQLSRV driver, please [disable MARS](https://learn.microsoft.com/en-us/sql/connect/php/how-to-disable-multiple-active-resultsets-mars?view=sql-server-ver16) using/on the connection option.
> 
> Sample code (SQLSRV driver):
> 
> ```
> $serverName = "<Babelfish server FQDN>, <Port number>";
> $connectionInfo = array( "Database"=>"<Database name>", "UID"=>"<userID>", "PWD"=>"<password>","MultipleActiveResultSets"=>false);
> sqlsrv_configure('WarningsReturnAsErrors',0);
> $conn = sqlsrv_connect( $serverName, $connectionInfo);
> ```
> 
> Sample code (PDO_SQLSRV driver):
> 
> ```
> $serverName = "<Babelfish server FQDN>, <Port number>";
> $database = "<Database name>";
> $uid = "<userID>";
> $pwd = "<password>";
> 
> try
> {
>   $conn = new PDO( "sqlsrv:server=$serverName; Database=$database; MultipleActiveResultSets=false", $uid, $pwd );
> }
> catch(PDOException $e)  
> {
>   $e->getMessage();
> }
> ```
to fix the problem I changed the database config 
`
        'sqlsrv' => [
            ......
            'trust_server_certificate' => 'true',
            'multiple_active_result_sets' => false,
        ],`
and then the problem was solved.
Thank you @syuaip for for the explanation.
