### ISSUE TITLE
[Bug]: cannot give db_owner permission to user

### ISSUE THREAD

**Issue by kewinbrand** [babelfish-for-postgresql/babelfish_extensions#2515]
### What happened?

when I try to add a user as db_owner the following error happens

```
Msg 33557097, Level 16, State 1, Line 6
Cannot make a role a member of itself.
```

i am using the following script
```sql
create database test123
use test123
create user [Octopus] FOR LOGIN [Octopus]
EXEC sp_addrolemember N'db_owner', N'Octopus'
```

we are using BABEL_4_X_DEV branch

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Relevant log output

```shell
Msg 33557097, Level 16, State 1, Line 6
Cannot make a role a member of itself.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
This is a known current limitation: Babelfish supports only a single dbo user. Background is the way PG roles are used to implement the dbo user.

**Comment by kewinbrand** [comment]
alright, but this is a new database, there are no users linked to it. are you referring to the babelfish installation user?

**Comment by robverschoor** [comment]
In every database , there is the **dbo** user who is the database owner. Technically **db_owner** is a role and any user who is a member of that role will have **dbo** privileges. In Babelfish, currently **db_owner** can have only one member and that's **dbo**.  When trying to add another member, you will get the error message as shown above.

**Comment by kewinbrand** [comment]
hmm now i see
so i created that database as ```babelfish_user```, and consequently the owner became him
to fix the problem I changed the database owner using the command ```ALTER AUTHORIZATION ON DATABASE::[test123] TO [Octopus]``` and then the problem was solved
thank you for the explanation
