### ISSUE TITLE
Is their any support for babelfish

### ISSUE THREAD

**Issue by madanparedla** [babelfish-for-postgresql/babelfish_extensions#2572]
Hi can any once let me know if there is any support for babelfish for postgresql

**Comment by suprio-amzn** [comment]
@madanparedla: Could you please elaborate on what you meant by the above -- _support for babelfish for postgresql_?

**Comment by madanparedla** [comment]
yes i am setting up babelfish in our EC2 instance and getting some issue to resolve so looking for support.

**Comment by kuntalghosh** [comment]
1. Which steps are you following?
2. In which step are you getting an error?
3. What's the error?

**Comment by suprio-amzn** [comment]
@madanparedla: This is the forum to get support on Babelfish for PostgreSQL. If you post your problem with details and with enough information for a reproduction, community members will be able to help you. Please review the following links:

1. https://babelfishpg.org/docs/faq/getting_help/
2. https://babelfishpg.org/docs/faq/#how-can-i-report-a-bug
