### ISSUE TITLE
Create multiple babelfish databases for each database from sql server

### ISSUE THREAD

**Issue by madanparedla** [babelfish-for-postgresql/babelfish_extensions#2573]
How to create multiple databases in babelfish

**Comment by robverschoor** [comment]
Sounds like your cluster was created in "single-db" mode?  If you want to create more than one database, the cluster must be created in "multi-db" mode. You cannot change the migration mode, so you'd have to create a new cluster.
See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-architecture.html and https://babelfishpg.org/docs/installation/single-multiple/

**Comment by madanparedla** [comment]
can you please share steps how to create new cluster and in multi-db enabled.

**Comment by robverschoor** [comment]
See the documentation: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-create.html

**Comment by madanparedla** [comment]
i am setting up in physical server not in aurora RDS

**Comment by robverschoor** [comment]
See the other link which I posted above for the standalone setup procedure
