### ISSUE TITLE
Windows Capable?

### ISSUE THREAD

**Issue by Sawsbucky** [babelfish-for-postgresql/babelfish_extensions#263]
I've found and seen info about Linux, but I'm having trouble finding any instructions for installing babelfish on a Windows OS-my priority is installing the dependencies.

Any help or feedback on the matter would be greatly appreciated.

**Comment by max-webster** [comment]
I'm in the same boat. I'll consult with the dev team and reply back here.

**Comment by suprio-amzn** [comment]
@Sawsbucky: Unfortunately we are not planning to support Windows builds for now.

**Comment by staticlibs** [comment]
Just in case someone will be looking for Windows builds, I am doing Windows builds in [this repo](https://github.com/wiltondb/wiltondb). These builds are done from sources modified for downstream WiltonDB project. If the plan to have Windows support in upstream Babelfish will ever be reconsidered - I can happily contribute Windows patches for that.
