### ISSUE TITLE
[Bug]: Cannot view AWS RDS Aurora tables in SSMS (SQL Server Management Studio)

### ISSUE THREAD

**Issue by umayyanathan** [babelfish-for-postgresql/babelfish_extensions#2668]
### What happened?

I am able to connect to the AWS RDS Aurora instance from SSMS by choosing the database in the Object Explorer --> Connect --> Connection Properties --> Choose 'Test' database. 

However, I cannot view the Database or Tables in the Object Explorer in SSMS.  See screenshot attached.  To the contrary and interestingly, I am able to get results successfully when I ran a SELECT statement in the Query window of SSMS.  

Please advise what is missing to view the database objects in the object explorer.

Uma

### Version

BABEL_4_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by umayyanathan** [comment]
![SQL Server Object Explorer](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/110237897/76de43fc-7420-4630-8a3c-54d40253a6b4)

**Comment by umayyanathan** [comment]
![No Database or Tables](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/110237897/555f0c17-ca5f-4879-a91f-02d302f0b1c9)

**Comment by umayyanathan** [comment]
For reference, I have attached screenshots.

**Comment by suprio-amzn** [comment]
@umayyanathan: Please provide version info for SSMS as well as Babelfish.

**Comment by umayyanathan** [comment]
AWS RDS Aurora (PostGres 15.3 with BabelFish) has the BabelFish version 3.3.0
SSMS version is 19.3.4.0

**Comment by umayyanathan** [comment]
![babelfishVersion](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/110237897/6a811cae-640e-4e66-a521-3b46605c3ec6)

**Comment by suprio-amzn** [comment]
@umayyanathan: If you are using Babelfish for Aurora PostgreSQL, please upgrade to the latest version either to [Babelfish for Aurora 3.5](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraBabelfish.Updates.html#AuroraBabelfish.Updates.35X) or [Babelfish for Aurora 4.1](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraBabelfish.Updates.html#AuroraBabelfish.Updates.41X) where a similar issue has been fixed with SSMS version 19.2, I suspect the same exists with SSMS 19.3 also.

**Comment by umayyanathan** [comment]
Thank you @suprio-amzn.  I will try and keep you posted.

**Comment by umayyanathan** [comment]
Sorry, same issue...

**Comment by umayyanathan** [comment]
![ssms](https://github.com/babelfish-for-postgresql/babelfish_extensions/assets/110237897/d970c63d-3317-4021-b52f-1c663bc1cc14)

**Comment by umayyanathan** [comment]
I deleted the RDS Aurora 3.5 babelfish test instance completely and re-created with the latest version (for PostGres 16.2).  Now the tables are showing up in SSMS.  

Thank you very much for your reference and help @suprio-amzn.

**Comment by shalinilohia50** [comment]
I have also tried with SSMS version 19.3.4.0 (latest). 
There is an issue with the [Babelfish version 3.4 ](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraBabelfish.Updates.html#AuroraBabelfish.Updates.34X ) where I couldn't view the Database in the Object Explorer in SSMS. As @suprio-amzn  mentioned, it is resolved in [Babelfish version 3.5](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraBabelfish.Updates.html#AuroraBabelfish.Updates.35X).
