### ISSUE TITLE
[Bug]: BABEL_4_1_0__PG_16_2 fails to build when using --with-openssl

### ISSUE THREAD

**Issue by jonathanpotts** [babelfish-for-postgresql/babelfish_extensions#2694]
### What happened?

BABEL_4_1_0__PG_16_2 fails to build when using `--with-openssl`. I was able to successfully build BABEL_2_3_0__PG_14_6 through BABEL_4_0_0__PG_16_1 when using `--with-openssl`.

I am following the instructions as provided in the INSTALLING.md file but adding `--with-openssl` as indicated by https://github.com/babelfish-for-postgresql/babelfish_extensions/tree/BABEL_4_X_DEV/contrib#build-the-postgres-engine.

### Version

BABEL_4_X_DEV (Default)

### Extension

babelfishpg_tds

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Relevant log output

```shell
#47 0.604 src/backend/tds/tds-secure-openssl.c: In function 'my_sock_read':
#47 0.604 src/backend/tds/tds-secure-openssl.c:859:31: error: dereferencing pointer to incomplete type 'BIO' {aka 'struct bio_st'}
#47 0.604   859 | #define BIO_get_data(bio) (bio->ptr)
#47 0.604       |                               ^~
#47 0.604 src/backend/tds/tds-secure-openssl.c:870:35: note: in expansion of macro 'BIO_get_data'
#47 0.604   870 |   res = secure_raw_read(((Port *) BIO_get_data(h)), buf, size);
#47 0.604       |                                   ^~~~~~~~~~~~
#47 0.614 make: *** [<builtin>: src/backend/tds/tds-secure-openssl.o] Error 1
#47 ERROR: process "/bin/sh -c make && make PG_CONFIG=${PG_CONFIG} install" did not complete successfully: exit code: 2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by staticlibs** [comment]
Hi, [this commit](https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/83e80a380b92d4e560c66b3069259a0bf7a7c9ab) seems to be missing in that branch.

**Comment by jonathanpotts** [comment]
If that's all that's needed to fix, can a hotfix be released with that commit applied?

**Comment by shardgupta** [comment]
We are checking the possibility to do a patch release with this fix, will keep you posted.

**Comment by shardgupta** [comment]
Created a patch release to fix this issue.

**Comment by shardgupta** [comment]
https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/releases/tag/BABEL_4_1_1__PG_16_2
