### ISSUE TITLE
[Question]: Executing ad-hoc T-SQL statements from the PostgreSQL sql connection.

### ISSUE THREAD

**Issue by yairlenga** [babelfish-for-postgresql/babelfish_extensions#27]
### Contact Details

yair.lenga@gmail.com

### What's the question?

Greetings,

I working on porting Sybase/ASE lib-ct application to Postgresql - trying to use Babelfish to speed up porting.

Is there a way to trigger execution of T-SQL sql statements from the PGSQL port.I'm not sure how babelfish was implemented, but I'm looking for something like

~~~
select ... from
    (tsql_eval($$
       merge ...
      update ...
      if ... begin
     end
$$))
~~~

Or Using temporary stored proc, assuming the TSQL is implemented as procedural language (similar to the way the extensions for Perl, Python works):

~~~
create procedure my_tsql_proc sa $$ 
    TSQL-STATEMENTS-AS-ABOVE
$$ language 't-sql' ;
call my_tsql_proc (...)
~~~

In theory, I can submit the above into the TSQL port. However, in my situation, there is new module, implemented with standard AWS tools (quick sight), connecting to Postgresql, which will query my database. I would like to pass the existing queries (currently in text file) into the quick sight, so that it can extract the data via the Postgresql channel.

From logistical point of view, I'm not able to have Quicksight  tool reconfigured to connect to the TSQL port via TDS - the tools are owned by a different team, and the connection was already spec'd, implemented and approved.

My questions/requests:
* Is there a way to submit T-SQL text queries to the babelfish engine via the an SQL function ? 
* If not possible, can this be done using create/execute (temp) procedure ?
* Any other creative idea to achieve the same ?

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
You should create T-SQL language objects through the Babelfish TDS port, and invoke them through the TDS port. Likewise, You should create PG/plSQL language objects through the PG port, and invoke them through the PG port.  While it may technically be possible to mix SQL dialects in a single session, this may behave differently (especially related to transactions and error handling) than it would when invoked through the corresponding session only.

**Comment by max-webster** [comment]
As the scenario in the original question is unsupported / impractical, I'll close the issue now.
