### ISSUE TITLE
Is it possible to create CDC in babelfish db

### ISSUE THREAD

**Issue by madanparedla** [babelfish-for-postgresql/babelfish_extensions#2723]
Hi @ALL,

Is it possible to enable change data capture in babelfish db.

**Comment by shardgupta** [comment]
Babelfish is adding support for PostgreSQL native logical replication in upcoming release. This might help to replicate changes from source tables to destination table. You can give it a try on BABEL_4_X_DEV or BABEL_3_X_DEV branches.
