### ISSUE TITLE
Babelfish production server

### ISSUE THREAD

**Issue by madanparedla** [babelfish-for-postgresql/babelfish_extensions#2816]
Hi @all,

Anyone from INDIA who is working on babelfish onpremise in ubuntu who can connect and help on setup production server please

**Comment by staticlibs** [comment]
@madanparedla , if you can share specific requirements for Ubuntu deployment (here, or in [babelfish-for-postgresql discussions](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/discussions) or in [babelfish_postgresql_towel](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel)) others may be able to suggest solutions.

IMHO "Ubuntu production deployment" topic is quite broad and can span from "run `./bin/postgres -D` over SSH+Screen" up to "use some on-premise k8s setup (from [EDB](https://github.com/cloudnative-pg/cloudnative-pg), [Zalando](https://github.com/zalando/postgres-operator) etc) with Babelfish-enabled Postgres".
