### ISSUE TITLE
[Bug]: Relation 'table_name' does not exist

### ISSUE THREAD

**Issue by xinghengYu** [babelfish-for-postgresql/babelfish_extensions#285]
### What happened?

I have installed a Babelfish database and cab connect via SSMS or Navicat on TDS protocol.
running the SQL query as below is OK:
select * from PROJECT

but when I open a C/S hierarchy software to get the data via the same SQL.
it shows me 'relation 'PROJECT' does not exist.'

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kuntalghosh** [comment]
Hi @xinghengYu,

It's possible that the software is accessing some catalog information that we've not yet implemented in Babelfish. It'll be great if you can share the queries that the software sends to Babelfish server.

You can enable [log_statement](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-STATEMENT) = 'all' in postgresql.conf file. This parameter will log all the queries in the logfile. Thanks.

**Comment by suprio-amzn** [comment]
@xinghengYu: Were you able to use suggestion from @kuntalghosh above and produce verbose log output?
