### ISSUE TITLE
Debezium to stream data in babelfish

### ISSUE THREAD

**Issue by kranthi1385** [babelfish-for-postgresql/babelfish_extensions#2870]
Hi Experts,

Is it possible to configure debezium and stream data using kafka in Babelfish. If yes can you please suggest the steps.

**Comment by shardgupta** [comment]
I believe you are talking about https://debezium.io/documentation/reference/stable/connectors/postgresql.html. We haven't tried this tool, so can't really say if would work or not. If you have used this previously with PostgreSQL you can give it a try for Babelfish. The steps would remain same as we configure the logical replication slots using the PostgreSQL port only. If you face any specific issue, you can post it here.

**Comment by shardgupta** [comment]
@kranthi1385 , We haven't received any communication on this in last few days. Feel free to close this ticket if this is no longer needed.

**Comment by kranthi1385** [comment]
@shardgupta sorry we are working on other development and kept this in hold for now will close the ticket
