### ISSUE TITLE
[Question]: How can i create a non sysadmin user for an app connection?

### ISSUE THREAD

**Issue by EricOddz** [babelfish-for-postgresql/babelfish_extensions#2965]
What happened?

Hi, i try to create an user for a connection for an app. I dont want to give the user the sysadmin role and instead create a separate user for it. I used the following commands:

`USE TEST_DB;

CREATE ROLE app_role;
GRANT CONNECT TO app_role; 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_role;
CREATE LOGIN app_user WITH PASSWORD = 'change_it';

ALTER ROLE app_role ADD MEMBER app_user;`

If i want to login with that user via the MSSQL port i got the following error:

permission denied for database "babelfish_db" ClientConnectionId:xxx

I dont know how to create such users or is that even possible?

Version
BABEL_4_2_0

Extension
AWS RDS Postgres with Babelfish

**Comment by staticlibs** [comment]
Hi,

I can think of two scenarios with a non-sysadmin login for a particular T-SQL DB:

1. the DB is owned by this login:

```tsql
create login login_1 with password = 'login_1'
create database db_1
alter authorization on database::db_1 to login_1
```

Check that this login owns the DB:

```tsql
select name, owner, crdate
from sys.babelfish_sysdatabases
where name = 'db_1'
```

Check that this login is not sysadmin:

```tsql
select usename, usesuper from pg_user
where usename = 'login_1'
```

2. the user is created for this login inside the DB and particular permissions are assigned to that user:

```tsql
create login login_2 with password = 'login_2'
create database db_2
use db_2
create user user_2 for login login_2
```
```tsql
use db_2
create table tab_1 (col1 int)
insert into tab_1 values (42)
grant select on tab_1 to user_2
```

Check user and login names for the current session:

```tsql
select current_user
select suser_name()
```

Check permissions assigned to the user:

```tsql
select
    rel.relname,
    nsp.nspname,
    gtor.rolname as grantor,
    gtee.rolname as grantee,
    acl.privilege_type,
    acl.is_grantable
from pg_class rel
join aclexplode(coalesce(relacl, acldefault('r', relowner))) acl on 1 = 1
join pg_namespace nsp on rel.relnamespace = nsp.oid
join pg_roles gtor on acl.grantor = gtor.oid
join pg_roles gtee on acl.grantee = gtee.oid
where gtee.rolname = 'db_2' + '_' + 'user_2'
```

**Comment by EricOddz** [comment]
thank you very much for your response. I really like the way you doing it. But i still got the error if i want to connect with that user

permission denied for database "babelfish_db" ClientConnectionId:.....

Here is my connection string:
jdbc:sqlserver://;serverName=test-eu.cluster-xxxxx.eu-central-1.rds.amazonaws.com;databaseName=test_db

Port: 1433

if i give them the sysadmin role, erverything works well. Maybe i need to add the permissions via postgres for the babelfish_db?

**Comment by shardgupta** [comment]
Approach 1, suggested by @staticlibs is the preferred one.
```
create login login_1 with password = 'login_1'
create database db_1
alter authorization on database::db_1 to login_1
```

You need to make sure that there is no user mapped with login_1, else it will through the error.

**Comment by staticlibs** [comment]
@EricOddz 

I suggest to re-check this on a clean DB cluster. These examples work for me without adding any permissions on Postgres connection. That you are seeing physical DB name in error messages does not look right. For example, if you try to connect under a non-sysadmin user to a wrong T-SQL DB, error like this should be reported:

```
login error: Cannot open database "db_other" requested by the login. The login failed
```

**Comment by robverschoor** [comment]
> thank you very much for your response. I really like the way you doing it. But i still got the error if i want to connect with that user
> 
> permission denied for database "babelfish_db" ClientConnectionId:.....
> 
> Here is my connection string: jdbc:sqlserver://;serverName=test-eu.cluster-xxxxx.eu-central-1.rds.amazonaws.com;databaseName=test_db
> 
> Port: 1433
> 
> if i give them the sysadmin role, erverything works well. Maybe i need to add the permissions via postgres for the babelfish_db?

Granting/revoking permissions should be done in T-SQL. While it may be possible to do it in PG SQL, this is strongly advised against since this may lead to unwanted side-effects, either now or in the future (e.g. when upgrading to a newer version of Babelfish).

**Comment by EricOddz** [comment]
thank you everyone for the suggestions! I will try it on a new clean cluster and then come back to you.

@robverschoor im using the port 1433 so its the mssql connection with t-sql.

**Comment by EricOddz** [comment]
okay, thank you very much. On a new clean cluster everything went fine with the following code. But i dont know why.

`create login login_1 with password = 'login_1'
create database db_1
alter authorization on database::db_1 to login_1`
