### ISSUE TITLE
[Question]: Does babelfish not support replication?

### ISSUE THREAD

**Issue by zhaowcheng** [babelfish-for-postgresql/babelfish_extensions#2988]
### What happened?

I created a standby instance using pg_basebackup with the `-X stream` option, but when I started the standby instance I got the following logs:
![image](https://github.com/user-attachments/assets/68779746-fe7b-46ad-8bdb-04884c7d78f4)

### Version

BABEL_4_X_DEV (Default)

### Extension

None

### Which flavor of Linux are you using when you see the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sksql** [comment]
Babelfish does support **native** logical replication. See e.g. [link](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Replication.Logical.html)

Babelfish does not yet support the **extension** pglogical. See [link](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-limitations.html)

pg_basebackup is not yet tested and supported.
