### ISSUE TITLE
[Bug]: Link to build instructions in README is wrong

### ISSUE THREAD

**Issue by andreasscherbaum** [babelfish-for-postgresql/babelfish_extensions#3]
The README says:
```
Build instructions can be found here.
```
The link under `here` points to: https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/contrib/README.md

This link points to a non-existent website.

**Comment by 3manuek** [comment]
This has been fixed in https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/8. cc/ @gopinathpai 

Thanks @andreasscherbaum for the report!

**Comment by gopinathpai** [comment]
@andreasscherbaum. Thank you for reporting the Issue. It has been fixed. https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/BABEL_1_X_DEV/contrib/README.md
