### ISSUE TITLE
May I ask what is wrong in the picture? There is no error in compiling the installation, but there is an error in installing extension. The Linux version is Centos7.9.

### ISSUE THREAD

**Issue by weiya1990** [babelfish-for-postgresql/babelfish_extensions#30]
### Contact Details

weiy@runsa.cn

### What's the question?

error pictur
![插件报错截图](https://user-images.githubusercontent.com/38902618/140893416-ef39312d-6365-4ffd-9ca1-82ae145b9865.jpg)
e

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3manuek** [comment]
Hi @weiya1990 , can you share more details about the environment and the steps done to reproduce this issue?
