### ISSUE TITLE
[Bug]: OBJECT_ID function requires the default schema "dbo" in babelfish 4.2

### ISSUE THREAD

**Issue by stephanep-croesus** [babelfish-for-postgresql/babelfish_extensions#3010]
### What happened?

Before 4.2 it is working:
SELECT OBJECT_ID('table_name') 
SELECT OBJECT_ID('procedure_name') 

But in 4.2.. we must specify the default schema "dbo"
SELECT OBJECT_ID('dbo.table_name')
SELECT OBJECT_ID('dbo.procedure_name')
else we got this error "SQL Server did not return a response. The connection has been closed."

### Version

BABEL_4_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Relevant log output

```shell
SQL Server did not return a response. The connection has been closed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
I cannot reproduce this issue:

```
1> SELECT CAST(SERVERPROPERTY('BabelfishVersion') AS VARCHAR)
2> go
serverproperty
------------------------------
4.2.0

(1 rows affected)

1> create table t(a int)
2> go
1> SELECT OBJECT_ID('dbo.t')
2> go
object_id
-----------
      36914

(1 rows affected)

1> SELECT OBJECT_ID('t')
2> go
object_id
-----------
      36914

(1 rows affected)
```

**Comment by stephanep-croesus** [comment]
We found the source of our problem.
We were letting the `pg_dump --create` option generate and execute the CREATE DATABASE statement on postgres whereas it should have been executed through babelfish first before pg_restoring.

**Comment by suprio-amzn** [comment]
Btw, you should be using **bbf_dump/bbf_dumpall** utilities. See [the docs](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/wiki/Babelfish-dump-and-restore).

**Comment by stephanep-croesus** [comment]
Thanks a lot
