### ISSUE TITLE
DBMAIL in babelfish.

### ISSUE THREAD

**Issue by kranthi1385** [babelfish-for-postgresql/babelfish_extensions#3081]
How can we configure PGMAIL or any other extensions to send email from babelfish

**Comment by staticlibs** [comment]
@kranthi1385 

You can use `COPY` command with the `PROGRAM` option to invoke a script or some utility (for example, [swaks](https://github.com/jetmore/swaks)) to send emails. See the [example of calling pg_dump](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/issues/6#issuecomment-2256054607).

**Comment by suprio-amzn** [comment]
One way to send email from the database (if it is on Aurora PostgreSQL) is described here: https://docs.aws.amazon.com/dms/latest/sql-server-to-aurora-postgresql-migration-playbook/chap-sql-server-aurora-pg.management.databasemail.html#chap-sql-server-aurora-pg.management.databasemail.pg
