### ISSUE TITLE
Need details on plan for replication from on-premise machine babelfish + postgreSQL to AWS Aurora cloud Babelfish +PostgreSQL

### ISSUE THREAD

**Issue by psrinivasa2** [babelfish-for-postgresql/babelfish_extensions#3119]
Need to understand replication steps from general on-premise machine babelfish + postgreSQL to AWS Aurora cloud Babelfish +PostgreSQL

**Comment by chandra-pathivada** [comment]
You can use AWS DMS to replicate on-prem babelfish to Babelfish for Aurora PostgreSQL

**Comment by psrinivasa2** [comment]
can you please share detail steps on it

**Comment by chandra-pathivada** [comment]
sure below are the links
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.Babelfish.html
