### ISSUE TITLE
[Bug]: cannot create fk constraint in 1433 endpoint; apparently can create in 5432 endpoint only.

### ISSUE THREAD

**Issue by univsocal** [babelfish-for-postgresql/babelfish_extensions#355]
### What happened?

when attempting to create FK i 1433 endlpoint - get error

ALTER TABLE AdditionalDTCTitleData ADD CONSTRAINT FK_Holiday FOREIGN KEY (Holiday) REFERENCES Holiday(HolidayNo)

Msg 33557097, Level 16, State 1, Line 67
column "holiday" referenced in foreign key constraint does not exist

--- ---------

Babelfish for Aurora Postgres with SQL Server Compatibility - 12.0.2000.8 May 27 2022 05:26:23 Copyright (c) Amazon Web Services PostgreSQL 13.7 on aarch64-unknown-linux-gnu

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Other

### Relevant log output

```shell
Babelfish for Aurora Postgres with SQL Server Compatibility - 12.0.2000.8 May 27 2022 05:26:23 Copyright (c) Amazon Web Services PostgreSQL 13.7 on aarch64-unknown-linux-gnu
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
There is not enough information to reproduce the issue. Please provide the DDL for tables **AdditionalDTCTitleData** and **Holiday**

**Comment by univsocal** [comment]
wow thanks for the quick response. we are in the process of converting 1000+ sql server tables to postgres thru the use of aws-dms and babelfish. wanted to please know if we are doing something incorrect by attempting to add fk thru 1433 endpoint. 

[AdditionalDTCTitleData.txt](https://github.com/babelfish-for-postgresql/babelfish_extensions/files/9031947/AdditionalDTCTitleData.txt)
[holiday.txt](https://github.com/babelfish-for-postgresql/babelfish_extensions/files/9031951/holiday.txt)
.

**Comment by univsocal** [comment]
we created the tables empty in 1433 endpoint thru extracted ddl and then used DMS to load the table(s) data.  we are subsequently adding the indexes in 5432 endpoint to avoid the babelfish index very long suffixes, and then attempting to create the fk constraints in the babelfish 1433 endpoint.

**Comment by robverschoor** [comment]
When I run your DDL in Babelfish, it all works fine.

You should create the FK in Babelfish. When you create them in PG, things won't work (as you noticed) unless you figure out how to rename the schema.  The indexes are also best created in T-SQL.
Formally, Babelfish does not support this type of partly-in-T-SQL and partly-in-PG DDL for a single object. If you decide to go this way, you should be aware of a range of issues that you will need to take care of (we're publishing a doc on Babelfish-PG interoperability issues soon). For example, Babelfish may treat schema names differently than PG and you would have to adjust to that manually. One general downside of doing things partly in PG is that you may run into issues when upgrading to future Babelfish versions as it is not expected that indexes or FKs are created in this way in PG.  When doing things like permissions (on Babelfish objects) in PG, you may end up creating an unexpected security configuration for example.

**Comment by univsocal** [comment]
when i do try this in 1433 endpoint in SSMS as advised by aws tech - i do get an error.  you said works fine, but for me, generates an error. please did not want to take up too much of your time, and just wanted to know if i am doing something obviously wrong. 

thanks

![2022_0701_fk](https://user-images.githubusercontent.com/98920632/176976918-3d6ad3aa-c0f6-4ef0-b0a7-60caee6189ed.jpg)

**Comment by univsocal** [comment]
note - this is example of the NAMES of the indexes created in 1433 endpoint VS the NAMES of the indexes created in the 5432 endpoint

![2022_0701_indexes](https://user-images.githubusercontent.com/98920632/176977204-c47de48f-ea3d-4044-bf9b-58f27ab514ae.jpg)
t

**Comment by robverschoor** [comment]
This is what I get when I run the DDL. Please try that:

	1> CREATE TABLE [dbo].[AdditionalDTCTitleData](
	2>      [titleNo] [int] NOT NULL,
	3>      [dtcDescription] [nvarchar](4000) NULL,
	4>      [GTMProductionNo] [varchar](20) NULL,
	5>      [TmsId] [varchar](255) NULL,
	6>      [Holiday] [int] NULL,
	7>      [DTCProgramType] [int] NULL,
	8>      [DTCDayPart] [int] NULL,
	9>      [SEODescription] [varchar](500) NULL,
	10>     [MarketingAssets] [varchar](500) NULL,
	11>     [CoppaCompliance] [varchar](1) NULL,
	12>     [Franchise] [varchar](100) NULL,
	13>     [DtcDescriptionSpanish] [varchar](500) NULL,
	14>     [GracenoteDesc40Char] [varchar](40) NULL,
	15>     [GracenoteDesc60Char] [varchar](60) NULL,
	16>     [GracenoteDesc100char] [varchar](100) NULL,
	17>     [GracenoteDesc250char] [varchar](250) NULL,
	18>     [SeasonYear] [int] NULL,
	19>     [ReleaseDate] [datetime] NULL,
	20>     [AirOrderNo] [int] NULL,
	21>     [KidsOnly] [varchar](1) NULL,
	22>     [UserAdded] [int] NULL,
	23>     [DateAdded] [datetime] NULL,
	24>     [UserUpdated] [int] NULL,
	25>     [DateUpdated] [datetime] NULL,
	26>     [DelFlag] [varchar](1) NOT NULL,
	27>     [Sensitivity] [varchar](1) NULL,
	28>     [PeacockEpisodeNo] [int] NULL,
	29>     [originalNetwork] [int] NULL,
	30>     [IngestStatus] [varchar](250) NULL,
	31>     [IngestRequestedDate] [datetime] NULL,
	32>     [IngestCompleteDate] [datetime] NULL,
	33>     [AssociatedBrandId] [int] NULL,
	34>     [GTMVersionId] [int] NULL,
	35>     [CommercialContent] [varchar](1) NULL,
	36>     [SensitivityFlagNotes] [varchar](511) NULL,
	37>     [CommercialContentDescriptor] [varchar](500) NULL,
	38>     [Nudity] [varchar](1) NULL,
	39>     [SuppressVideoAds] [char](1) NULL,
	40>     [FulfillmentStatusLinear] [varchar](255) NULL,
	41>     [FulfillmentStatusNonLinear] [varchar](255) NULL,
	42>     [GmoIdLinear] [varchar](255) NULL,
	43>     [GmoIdNonLinear] [varchar](255) NULL,
	44>     [IngestRequestedDateLinear] [datetime] NULL,
	45>     [GracenoteDesc500char] [varchar](500) NULL,
	46>     [OriginCodeOwner] [varchar](80) NULL,
	47>     [LegalOwner] [varchar](80) NULL,
	48>     [FinancialOwner] [varchar](80) NULL,
	49>     [IngestDueDate] [datetime] NULL,
	50>     [IngestPriority] [int] NULL,
	51>     [DtcDescriptionGraceNoteFlag] [char](1) NOT NULL,
	52>     [TitleNameGraceNoteFlag] [char](1) NOT NULL,
	53>     [StudioTradingPartner] [varchar](10) NULL,
	54>     [MerlinEPGOverrideFlag] [char](1) NULL,
	55>     [RunsInPlayDay] [int] NULL,
	56>     [AllowedRunsPerPlayDay] [int] NULL,
	57>     [UnlimitedRuns] [char](1) NOT NULL,
	58>     [RunsScheduled] [int] NULL,
	59>     [RunsAvailable] [int] NULL,
	60>     [PlaydayDefnNo] [int] NULL,
	61>     [NumberOfSegments] [bigint] NULL,
	62>     [TargetViewer] [int] NULL,
	63>     [FastTrack] [char](1) NOT NULL,
	64>     [RecordForVOD] [char](1) NOT NULL,
	65>     [GNRatingOverrideFlag] [char](1) NULL,
	66>     [UnifiedVersionId] [varchar](20) NULL,
	67>     [CheckUnifiedVersionId] [bit] NOT NULL,
	68>     [SegmentationTypeNo] [int] NULL,
	69>     [FullQC] [char](1) NULL,
	70>     [DayDate] [char](1) NOT NULL,
	71>     [NFLConsent] [char](1) NOT NULL,
	72>     [StagingFulfillmentStatus] [varchar](255) NULL,
	73>     [UHD] [char](1) NULL,
	74>     [UHDFulfillmentStatus] [varchar](255) NULL,
	75>     [Sponsor] [varchar](60) NULL,
	76>     [DayNo] [int] NULL,
	77>  CONSTRAINT [pk_titleno] PRIMARY KEY CLUSTERED
	78> (
	79>     [titleNo] ASC
	80> )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
	81> ) ON [PRIMARY]
	82> GO
	1> CREATE TABLE [dbo].[Holiday](
	2>      [HolidayNo] [int] IDENTITY(1,1) NOT NULL,
	3>      [Holiday] [varchar](50) NOT NULL,
	4>      [UserAdded] [int] NOT NULL,
	5>      [DateAdded] [datetime] NOT NULL,
	6>      [UserUpdated] [int] NULL,
	7>      [DateUpdated] [datetime] NULL,
	8>      [DelFlag] [char](1) NOT NULL,
	9> PRIMARY KEY CLUSTERED
	10> (
	11>     [HolidayNo] ASC
	12> )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	13> ) ON [PRIMARY]
	14> GO
	1> ALTER TABLE AdditionalDTCTitleData ADD CONSTRAINT FK_Holiday FOREIGN KEY (Holiday) REFERENCES Holiday(HolidayNo)
	2> GO
	1>

**Comment by suprio-amzn** [comment]
@univsocal : Could you try with the Babelfish 2.1.0 release again?

**Comment by suprio-amzn** [comment]
Please reopen if you can reproduce the issue with the latest release as mentioned above.
