### ISSUE TITLE
how can I access data created by pg

### ISSUE THREAD

**Issue by HelloWorld-9527** [babelfish-for-postgresql/babelfish_extensions#371]
Hello, may I ask a question？

I have a scene that needs migrate data into babelfish pg  and access by sqlserver tds.
how can I get data by 1433(port for sqlserver)  while the table or object is created by pg?

create table t1 by pg port：
```
bin/psql -d babelfish_db
babelfish_db=# set search_path=master_dbo;
SET
babelfish_db=# create table master_dbo.t1 (id int);
CREATE TABLE
babelfish_db=# \dt
                List of relations
   Schema   |      Name      | Type  |   Owner    
------------+----------------+-------+------------
 master_dbo | t1             | table | babelfish


sqlcmd -S ip,1433 -U babelfish_user
1> select * from t1;
2> go
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 1
permission denied for table t1




while I create table in sqlcmd (by port for sqlserver)

sqlcmd -S ip,1433 -U babelfish_user
1> create table t2 (id int);
2> go

I can access data by pg port

bin/psql -d babelfish_db -p 5432
babelfish_db=# select * from master_dbo.t2;
 id 
----
(0 rows)

```

That is, I can't access pg data by tds,  but pg can access sqlserver port data
Can I get and manipulate  data  by sqlserver port （1433， tds） while the data is created  by pg?

**Comment by robverschoor** [comment]
Babelfish is designed to provide T-SQL semantics on top of PostgreSQL through the T-SQL
dialect via the TDS port. The Babelfish database can also be accessed through the standard
PostgreSQL port with PostgreSQL SQL statements. When PostgreSQL statements or PostgreSQL access occur in the context of Babelfish, interference between PostgreSQL and Babelfish may occur, potentially affecting syntax, semantics, and compatibility with future releases of Babelfish.

Babelfish guarantees that a table (or other SQL object) that is created by T-SQL in a TDS connection in Babelfish, will be accessible with the same permissions when connecting through the PostgreSQL port with the same user as when connecting to TDS, without running any additional PostgreSQL statements. However, the other way around is not guaranteed: when creating an object in PostgreSQL, it may not be visible or accessible from a TDS connection, or it may be accessible with different permissions.
It may be possible to grant permissions on PG level to resolve access issues for objects created in PG, but this could potentially lead to interference with how Babelfish manages  the permissions. As a result, this might lead to a security configuration that does not behave as expected (e.g. a security hole).
To avoid such issues, schemas and objects that will be accessed from PostgreSQL, should be
created in T-SQL.

**Comment by suprio-amzn** [comment]
Detailed answer provided - please also see Interoperability guidance [https://babelfishpg.org/docs/usage/interoperability](https://babelfishpg.org/docs/usage/interoperability/).
