### ISSUE TITLE
[Question]: What if for MySQL?

### ISSUE THREAD

**Issue by ghost** [babelfish-for-postgresql/babelfish_extensions#4]
### Contact Details

hufeng1987@gmail.com

### What's the question?

I have a question!  What if for MySQL protocol, let We connect postgres , using mysql protocol?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JimFinnerty** [comment]
Thanks for the idea, @cnmade !   It might be possible to use the same approach for MySQL as Babelfish uses for SQL Server, but the data types, hooks, and extensions needed seem like they would be very different.  The protocol hooks could probably be reused, with an implementation for the MySQL wire protocol, though.  We are not planning to provide a solution for MySQL as part of the Babelfish for PostgreSQL project.

**Comment by ghost** [comment]
@JimFinnerty Thanks for let us know it. I know the AWS team has the best DB developers, who also provided us Aurora  for mysql/postgres. 
Sorry to hear that you won't provide mysql .
