### ISSUE TITLE
How to use SQL Server's 'Select FOR JSON PATH' & OPENJSON() in AWS RDS Babelfish DB

### ISSUE THREAD

**Issue by SwapnaSurya** [babelfish-for-postgresql/babelfish_extensions#428]
Below existing T-SQL code which generates table data in JSON format just by using the keyword FOR JSON PATH, include_null_values & OPENJSON(). How to implement the same in **Babelfish** (Aurora PostgreSQL enabling Bablefish cluster) query by connecting to SSMS itself?
_Need possible solutions_. Thanks in Advance!!

/** Sample Table data in MS SQL server ***/
```
CREATE TABLE [dbo].[Employee] (  
[id] INT,
[name] VARCHAR(25),
[state] VARCHAR(25) )

INSERT INTO [dbo].[Employee] values
(1,'Divya',NULL),
(2,'Akshay','Bengaluru'),
(3,'Kavya','Kolkata')

/** Fetching table data in JSON format ***/

DECLARE @json1 NVARCHAR(Max) 
SET @json1 = 
(
    SELECT * 
    FROM dbo.Employee WITH(nolock)
    FOR JSON PATH, INCLUDE_NULL_VALUES 
)
SELECT ',' AS [key],[value] FROM OPENJSON(@json1)
```

/** MS SQL results to **/
![Capture](https://user-images.githubusercontent.com/109748275/180248163-b6a7c89f-befe-4aa6-bcad-12aa7021d820.PNG)

**Comment by sksql** [comment]
FOR JSON is not supported. The supported functions are:
ISJSON( <JSON document> )
JSON_VALUE( <JSON document>, <path> )
JSON_QUERY(<JSON document> [, <path>] )
OPENJSON( <JSON document> [, path] ) [WITH clause]

Also note that currently a table alias after the WITH clause is not supported and there is a known phenomenon around using WITH clause in stored procedures.

Cheers,

/Stefan

**Comment by SwapnaSurya** [comment]
Thanks Stefan.
Let me know if this functionality can be implemented in future if any supportive functions introduced.

Thanks in Advance!
Swapna S

**Comment by suprio-amzn** [comment]
Hi @SwapnaSurya, yes these functions are on our roadmap.
