### ISSUE TITLE
[Question]: How can I use case sensitive identifiers?

### ISSUE THREAD

**Issue by chriscameron-vertexinc** [babelfish-for-postgresql/babelfish_extensions#445]
Hello!

I would like to be able to write queries for the TDS endpoint using quoted identifiers so that the Postgres tables/columns/etc end up with the correct capitalization.

For example, with:
`CREATE TABLE "Persons" ("Id" int);`

I would expect a table `Persons`, but instead I get `persons`.

I have tried experimenting with `babelfishpg_tsql.quoted_identifier` but it doesn't seem to do what I'm looking for.

Am I missing something obvious, or is this totally unsupported behaviour?

**Comment by sksql** [comment]
In what context / from what tool/statement do you expect the string "Persons" but get the lower case "persons" ?

Cheers,

/Stefan

**Comment by chriscameron-vertexinc** [comment]
Hi Stefan

For the example above I am:
1. Using DBeaver to connect to the TDS endpoint as MS SQL Server
2. Creating a new database "test"
3. Executing the above query `CREATE TABLE "Persons" ("Id" int);`
4. Checking the corresponding `dbo` schema on the PostgreSQL endpoint and confirming I get the table `persons`

I can also confirm that I get the same result when running the query via SSMS and verifying the result in DBeaver.

If you're asking about the use-case for my project: I have an enormous legacy application that uses UpperCamelCase naming conventions. I would like to keep the data as UpperCamelCase in the PostgreSQL database for human readability. I'm able to migrate my data into the PostgreSQL endpoint with the correct capitalization, but I'm unable to query it via the TDS endpoint because everything is being forced to lowercase.

**Comment by max-webster** [comment]
> I would like to keep the data as UpperCamelCase in the PostgreSQL database for human readability.

Looks like currently this isn't supported. The original name gets stored with its original case separately from the underlying Postgres table name in the metadata. If the access from the Postgres side is for querying only, is it practical to create views with the expected names (e.g. 'Persons' view defined as 'select * from persons')?

**Comment by sksql** [comment]
I am not getting the same behavior, at least not using sqlcmd with BBF 1.2.2:

CREATE TABLE TableNameInCamelStyle(
        cOLUMNoNE       INT     IDENTITY PRIMARY KEY
        , COLUMNTWO     VARCHAR(100)    NOT NULL
        , columnthree   INT     NULL
)

INSERT INTO TableNameInCamelStyle VALUES
        ( 'string1', 1000 )
        , ( 'string2', 2000 )
        , ( 'string3', 3000 )
        , ( 'string4', 4000  )
        , ( 'string5', 5000 )


(5 rows affected)
SELECT CAST( SERVERPROPERTY('BabelfishVersion') AS VARCHAR ) AS "BabelfishVersion"

BabelfishVersion
------------------------------
1.2.2

(1 rows affected)
SELECT * FROM TableNameInCamelStyle

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM tablenameincamelstyle

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM TABLENAMEINCAMELSTYLE

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SET QUOTED_IDENTIFIER ON

SELECT * FROM "TableNameInCamelStyle"

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM "tablenameincamelstyle"

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM TableNameInCamelStyle

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM tablenameincamelstyle

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM TABLENAMEINCAMELSTYLE

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SET QUOTED_IDENTIFIER ON

SELECT * FROM "TableNameInCamelStyle"

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM "tablenameincamelstyle"

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SELECT * FROM "TABLENAMEINCAMELSTYLE"

cOLUMNoNE   COLUMNTWO                                                                                            columnthree
----------- ---------------------------------------------------------------------------------------------------- -----------
          1 string1                                                                                                     1000
. . .

(5 rows affected)
SET QUOTED_IDENTIFIER OFF

**Comment by chriscameron-vertexinc** [comment]
I suspect if you're running all of these commands in sqlcmd then behind the scenes everything in the PostgreSQL database is still being stored lowercase.

Please can you try checking the PostgreSQL endpoint to see how the database is actually being stored? I suspect your tests would fail if you first made your table in PostgreSQL with mixed casing and then attempted to query it via sqlcmd.

For what it's worth I'm running Babelfish 2.1, I can confirm a more specific version once Docker starts co-operating...

**Comment by sksql** [comment]
This is post 2.1 (in development), it's the one I had handy at the time of writing:
```
[ec2-user@ip-172-31-94-239 ~]$ mypg
babelfish_db=# create table db1_dbo.TableOne( c1 INT );
CREATE TABLE
babelfish_db=# grant select on db1_dbo.TableOne to public;
GRANT
babelfish_db=# \q

[ec2-user@ip-172-31-94-239 ~]$ mybbf
1> select * from TableOne
2> go
c1
-----------

(0 rows affected)
1> set quoted_identifier on
2> go
1> select * from "TableOne"
2> go
c1
-----------

(0 rows affected)
1>
```

**Comment by suprio-amzn** [comment]
@chriscameron-vertexinc: Were you able to solve the case-sensitivity issue?
