### ISSUE TITLE
[Question]: create extension babelfishpg_tsql; ERROR: undefined symbol: TdsGetPGbaseType

### ISSUE THREAD

**Issue by HelloWorld-9527** [babelfish-for-postgresql/babelfish_extensions#49]
### Contact Details

254980222@qq.com

### What's the question?

According to the official document，I install babelfish( pg and extensions), but when i using psql and create extension, I met some error:
create extension babelfishpg_tsql;
ERROR:  could not load library "/home/babelfish/pgsql_babelfish/lib/babelfishpg_tsql.so": /home/babelfish/pgsql_babelfish/lib/babelfishpg_tsql.so: undefined symbol: TdsGetPGbaseType

Are there any steps that have been overlooked？
where can i know how to use babelfish after i installed?

### Relevant log output or information

```shell
2021-12-08 15:10:05.699 CST [120208] LOG:  database system is ready to accept connections
2021-12-08 15:10:13.095 CST [120272] ERROR:  could not load library "/home/babelfish/pgsql_babelfish/lib/babelfishpg_tsql.so": /home/babelfish/pgsql_babelfish/lib/babelfishpg_tsql.so: undefined symbol: TdsGetPGbaseType
2021-12-08 15:10:13.095 CST [120272] STATEMENT:  create extension babelfishpg_tsql;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gopinathpai** [comment]
Hi @HelloWorld-9527 could you please provide the exact steps you followed for the installation? We are unable to repro this issue. Thank you!

**Comment by HelloWorld-9527** [comment]
Thank you for answering.
I am follow this document : https://babelfishpg.org/docs/installation/compiling-babelfish-from-source/
my system is centos7，I have upgraded gcc/g++ to gcc (GCC) 8.3.1, cmake version 3.14.5

`export INSTALLATION_PATH=/home/babelfish/pgsql_babelfish`

```
cd ~/postgresql_modified_for_babelfish

./configure CFLAGS="-ggdb" \
--prefix=/home/babelfish/pgsql_babelfish \
--enable-debug \
--with-libxml \
--with-uuid=ossp \
--with-icu \
--with-extra-version=" Babelfish for PostgreSQL"

mkdir "$INSTALLATION_PATH"

make

cd contrib
make

cd ..
make install

cd  contrib
make install
```

and then following the document，install antlr4
```
# Dowloads the compressed Antlr4 Runtime sources on /opt/antlr4-cpp-runtime-4.9.2-source.zip 
sudo curl https://www.antlr.org/download/antlr4-cpp-runtime-4.9.2-source.zip \
  --output /opt/antlr4-cpp-runtime-4.9.2-source.zip 

# Uncompress the source into /opt/antlr4
sudo unzip -d /opt/antlr4 /opt/antlr4-cpp-runtime-4.9.2-source.zip

sudo mkdir /opt/antlr4/build 
cd /opt/antlr4/build

export EXTENSIONS_SOURCE_CODE_PATH=/home/babelfish/babelfish_extensions

# Generates the make files for the build
sudo cmake .. -DANTLR_JAR_LOCATION="$EXTENSIONS_SOURCE_CODE_PATH/contrib/babelfishpg_tsql/antlr/thirdparty/antlr/antlr-4.9.2-complete.jar" -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_DEMO=True
# Compiles and install
sudo make
sudo make install

sudo cp /usr/local/lib/libantlr4-runtime.so.4.9.2 "$INSTALLATION_PATH/lib"
```
then install the extensions
```
# Install babelfishpg_money extension
cd contrib/babelfishpg_money
make
make install

# Install babelfishpg_common extension
cd ../babelfishpg_common
make 
make install

# Install babelfishpg_tds extension
cd ../babelfishpg_tds
make 
make install

# Installs the babelfishpg_tsql extension
cd ../babelfishpg_tsql
make 
make install
```

start pg for babelfish,
i used psql and create extension

**Comment by HelloWorld-9527** [comment]
before installing babelfish extension, i have run several environment variables:
```
export PG_CONFIG=/home/babelfish/pgsql_babelfish/bin/pg_config
export PG_SRC=/home/babelfish/postgresql_modified_for_babelfish
```

and I started pg and psql is

```
$INSTALLATION_PATH/bin/initdb -D /home/babelfish/pgsql_babelfish/data
$INSTALLATION_PATH/bin/pg_ctl -D /home/babelfish/pgsql_babelfish/data start
$INSTALLATION_PATH/bin/psql -d postgres
```
I have changed the `postgresql.conf`
```
listen_addresses = '*'
shared_preload_libraries = 'babelfishpg_tds'
```

**Comment by kuntalghosh** [comment]
The language extension 'babelfishpg_tsql' has a dependency on 'babelfishpg_common' extension. Could you please check whether you've installed the other extension before creating the language extension? And, both the extensions should be created in the same psql session.

In order to avoid all the hassles, you can use the following command to install the dependencies automatically:
`create extension babelfishpg_tsql cascade;`

**Comment by HelloWorld-9527** [comment]
> 

![image](https://user-images.githubusercontent.com/23397598/145510577-74046007-1f36-44b4-bc0e-ab529d9661c3.png)

**Comment by gopinathpai** [comment]
@HelloWorld-9527,
@xaviersierra and @3manuek are validating the install instructions on centos7 environment. They will report back, once they have tested, with any findings. Thank you!

**Comment by HelloWorld-9527** [comment]
> @HelloWorld-9527, @xaviersierra and @3manuek are validating the install instructions on centos7 environment. They will report back, once they have tested, with any findings. Thank you!

Thank you for testing.
if you hava any finding，or something dependent packages I missed or installed wrong, or  update some step,  please contact me.

**Comment by 3manuek** [comment]
> before installing babelfish extension, i have run several environment variables:
> 
> ```
> export PG_CONFIG=/home/babelfish/pgsql_babelfish/bin/pg_config
> export PG_SRC=/home/babelfish/postgresql_modified_for_babelfish
> ```
> ...


Hi @HelloWorld-9527, can you retry recompiling the extensions adding the `cmake` env variable, please?

```
export PG_CONFIG=/home/babelfish/pgsql_babelfish/bin/pg_config
export PG_SRC=/home/babelfish/postgresql_modified_for_babelfish
export cmake=$(which cmake) 

EXT_CODE_PATH=/home/babelfish/<your extension repo location> ANTLR4_RUNTIME_LIBRARIES=/usr/include/antlr4-runtime ; \
    for EXT in babelfishpg_common babelfishpg_money babelfishpg_tds babelfishpg_tsql ; \
    do \
        cd ${EXT_CODE_PATH}/contrib/${EXT} ; \
        make clean && make && make install ; \
    done
```

**Comment by xaviersierra** [comment]
Hi @HelloWorld-9527 

I was able to install babelfish con centos7, to do that I have to upgrade gcc to 8.5.0:

The following script downloads and builld gcc. 
``` sh
yum update -y
# This install gcc 4.8.5, we would need to upgrade that later
yum install -y gcc gcc-c++ bzip2 make wget

mkdir /opt/gcc
cd /opt/gcc
# Downloading gcc 8.5.0
wget http://mirrors.up.pt/pub/gnu/gcc/gcc-8.5.0/gcc-8.5.0.tar.gz
tar -xzvf gcc-8.5.0.tar.gz

mkdir /opt/gcc/gcc-8.5.0/build
cd /opt/gcc/gcc-8.5.0

./contrib/download_prerequisites
cd /opt/gcc/gcc-8.5.0/build

sudo yum install -y kernel-devel zlib-devel glibc-devel
# Compiling gcc 8.5.0
../configure -enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr \
  --mandir=/usr/share/man --infodir=/usr/share/info \
  --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix \
  --enable-checking=release --disable-multilib --with-system-zlib --enable-__cxa_atexit \
  --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id \
  --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin \
  --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none \
  --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic \
  --with-arch_32=x86-64 --build=x86_64-redhat-linux

sudo make -j4 # If your hardware allows it increase the value 
sudo make install
```
Then I followed the installation steps as usual, until the antlr4 build. 

To compile antlr4, cmake version 3 is required. Unfortunately, the cmake of centos7 repositories is cmake 2

To install cmake version 3, I run the following script: 

``` sh
yum install -y http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-1.noarch.rpm
yum install -y cmake3
```
Therefore, to compile antlr4 I have to change the command to use following:

``` sh
cmake3 .. -DANTLR_JAR_LOCATION="$EXTENSIONS_SOURCE_CODE_PATH/contrib/babelfishpg_tsql/antlr/thirdparty/antlr/antlr-4.9.2-complete.jar" \
         -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_DEMO=True
make
make install
```
Then I proceed to compile the babelfish extensions.

Once I had babelfish running I was able to install the extensions with the command:

``` sql
CREATE EXTENSION IF NOT EXISTS "babelfishpg_tds" CASCADE;
```

**Comment by xaviersierra** [comment]
We currently don't support Babelfish on CentOS 7. We support CentOS 8. If you would like to contribute to the project by getting it running on CentOS 7, we'd welcome and support that. It will be beneficial for others who are on CentOS7. You could use the JDBC and ODBC test frameworks available.

**Comment by HelloWorld-9527** [comment]
thank you. 
Installation went smoothly on Ubuntu with no problems.
It can also be installed on centos7, I am using the babelfish now.  I will sort out the process and verify why it works when I am free, and list below.
