### ISSUE TITLE
[Question]: JDBC driver getTables returns empty result

### ISSUE THREAD

**Issue by mredeker** [babelfish-for-postgresql/babelfish_extensions#535]
### What happened?

Using the latest Java SQL-Server JDBC driver (or older versions) the following call returns an empty ResultSet:

`ResultSet result = connection.getMetaData().getTables(null, null, "%", new String[] { "TABLE" });`

I checked the Source of  the JDBC driver which calls the build-in function sp_tables.
When I call the function from SQL Server Management Studio, I receive the correct result:

`exec sp_tables @table_name='%', @table_owner = null, @table_qualifier=null,@table_type='TABLE'`

Also when executing the statement via JDBC, I receive the correct resutl:

`result = connection.prepareCall("exec sp_tables @table_name='%', @table_owner = null, table_qualifier=null,@table_type='TABLE'").executeQuery();`

I use the latest babelfish version on ubuntu 20.

Any ideas?

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by forestkeeper** [comment]
Could you add the jdbc version you have refered in the issue ? thanks

**Comment by mredeker** [comment]
Microsoft JDBC Driver 10.2.1
But also earlier version did not work.

**Comment by forestkeeper** [comment]
take a look at the server end and the jdbc debug, the sql running in those two places are actually different : 
when running : 
````
ResultSet result = connection.getMetaData().getTables(null, null, "%", new String[] { "TABLE" });
````
the sql actually executed is : 
````
EXEC sp_tables @P0, @P1, @P2, @P3
````

and for the query run explicitly , the sql actually executed is : 
````
exec sp_tables @table_name='%', @table_owner = null, @table_qualifier=null,@table_type='TABLE'
````

also tried this sql : 
````
EXEC sp_tables '%',null,null, 'TABLE'
````
it also works

So the problem must happen in the parameter P0,P1,P2,P3

**Comment by mredeker** [comment]
I doubt JDBC driver is mixing up P0,P1,P2,P3, otherwise JDBC driver would be having a major issue.
Maybe how babelfish translates parameters? Since call works without parameters it must be the parameters.
I dropped babelfish approach and use native postgres now.
