### ISSUE TITLE
[question]: Possible to call a PostgreSQL function from within Babelfish?

### ISSUE THREAD

**Issue by swechsler** [babelfish-for-postgresql/babelfish_extensions#544]
### What happened?

Babelfish 2.1 currently lacks support for `WAITFOR DELAY`; however, I note that PostgreSQL has the `pg_sleep()` function which would do the job just fine. Is there any way to call a Postgres function directly from Babelfish so we can implement our own missing functions rather than waiting for the team to add them?

### Version

BABEL_1_X_DEV (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
Indeed you can call pg_sleep directly from T-SQL using the EXECUTE keyword. A slightly bigger issue is how to convert the time argument to pg_sleep, E.g. **waitfor delay '01:02:03'** becomes **EXECUTE pg_sleep 3723.0** 
In fact, the Babelfish Compass tool will do this conversion for you when you use the **-rewrite** option (get Compass here: https://github.com/babelfish-for-postgresql/babelfish_compass/releases/latest)
