### ISSUE TITLE
[Question]: data migration

### ISSUE THREAD

**Issue by renzl321** [babelfish-for-postgresql/babelfish_extensions#56]
### What's the question?

My environment is that I want to migrate data from sqlserver to babelfish according to the official documentation generated DDL file using ssms tool and then import via sqlcmd tool with error."'CREATE DATABASE ON <database-file-spec>' is not currently supported in Babelfish",Every sql statement I my error,
![image](https://user-images.githubusercontent.com/30283157/147815246-e4b2daa0-6175-4069-a06b-183b8596bc02.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
You should probably enable the escape hatches which will ignore some (not all) of the unsupported syntax.  See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-strict.html and look for sp_babelfish_configure.

**Comment by khanna43** [comment]
Hi rcv-aws ,

Can we use bablefish to migrate SQL Server to PostgreSQL in on premise environments . ?.
I believe the postgreSQL for Bablefish along with extension is now open source project and can be used by anyone. ?
Please correct me if my understanding is not correct.

**Comment by suprio-amzn** [comment]
Yes, Babelfish for PostgreSQL (i.e. this Open Source project) which includes the Babelfish extensions and the PostgreSQL code base with the Babelfish patches applied can be used by anyone.
