### ISSUE TITLE
Support Dynamic SQL parameters upto 1500 

### ISSUE THREAD

**Issue by amuja** [babelfish-for-postgresql/babelfish_extensions#57]
Hi,

We have come across the scenario where application built on entity framework was failing due to dynamic sql generated by EF was producing 1500 parameters and currently PG only supports upto 100 parameters. Can we increase the limit of dynamic parameter processed on babelfish extension or loop through the parameters before the actual statements is parsed?

**Comment by robverschoor** [comment]
This should be discussed with product management and Babelfish dev mgmt first

**Comment by 3manuek** [comment]
Just adding extra information to this issue, the [SQL Server maximum capacity for function/procedure parameters](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?redirectedfrom=MSDN&view=sql-server-ver15) are:

- Parameters per stored procedure 2,100
- Parameters per user-defined function 2,100

Postgres function parameters are tied to [FUNC_MAX_ARGS](https://github.com/postgres/postgres/blob/master/src/include/pg_config_manual.h#L43) and BLCKSZ.

**Comment by suprio-amzn** [comment]
This issue is getting fixed in the upcoming release of Babelfish and is available in this commit (https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/89ed02ad2368efe9920b401dc296787159c43bb7).
