### ISSUE TITLE
Is it possible to add a linked server to babelfish?

### ISSUE THREAD

**Issue by Sjetware** [babelfish-for-postgresql/babelfish_extensions#577]
I've configured a local container to host babelfish with the default username and password on separate ports to not conflict with the running SQL and Postgres instances I already have running. Config setup:

* Postgres running in multi-db
* Username: babelfish_test
* Password: 12345678
* Container port mapping: (external -> internal)
** 1434 -> 1433
** 5433 -> 5432

I've been able to validate connectivity with  ✅ SSMS and with the ✅ sqlcmd command (so this works), and I can validate that SSMS from a single query window is able to access and show the data:

    sqlcmd -S localhost,1434 -U babelfish_user -P 12345678

And the current version being reported from within the container:

    Babelfish for PostgreSQL with SQL Server Compatibility - 12.0.2000.8 Nov  4 2021 19:18:41 Copyright (c) Amazon Web Services PostgreSQL 13.4 on x86_64-pc-linux-musl

However, I cannot get a linked server from SQL Server to connect to the Babelfish instance. Here's what I have tried so far:

* ❌ Added a system DSN with the credentials and port mapping, and then tried to add a linked server using the predefined DSN. No dice. 
* ❌Attempted to add the linked server by entering the credentials manually into a Linked Server config:

      -- I've tried providers SQLOLEDB, SQLNCLI11, MSOLEDBSQL, MSDASQL, MSDAOSP
      exec sp_addlinkedserver @server = 'BFISH', @srvproduct = N'', @datasrc='localhost,1434', @provider = 'MSOLEDBSQL'
      exec sp_addlinkedsrvlogin @rmtsrvname = 'BFISH', @useself = N'FALSE', @locallogin = null, @rmtuser = 'babelfish_user', @rmtpassword = '12345678'

Ultimately, the linked server is created, but transiting the link never seems to work. I either get metadata issues or errors that some functions in the sys space are missing.

Assume I run the following script within the "babelfish" connected SSMS query window (which runs successfully)

    create table [audit].[test_table]
    (
     	[id] int not null identity(1,1),
    	[text] varchar(200) not null
    )

    select * from audit.test_table

* If I try to query directly on this code:

      select * from BFISH.audit.test_table

I get response

     Msg 208, Level 16, State 1, Line 10
     Invalid object name 'BFISH.audit.test_table'.

Somewhat understandable, since traditional T-SQL would supply the database name. If I query on either version here

     select * from BFISH.[master].audit.test_table
     select * from BFISH.babelfish_db.audit.test_table

I get error:

     OLE DB provider "SQLNCLI11" for linked server "BFISH" returned message "Unspecified error".
     Msg 7303, Level 16, State 1, Line 10
     Cannot initialize the data source object of OLE DB provider "SQLNCLI11" for linked server "BFISH".

Is it possible to set up a linked server? What am I doing wrong?

**Comment by Sjetware** [comment]
The closest I've been able to get so far is configuring a System DSN for Sql Server Native Client 11.0:

* Name: BfishDsn
* Server: localhost,1434
* Credentials: babelfish_user, 12345678

Then when I configure the linked server in SQL server:

* Name: BFISH
* Data Source: BfishDsn
* Login with specific context: babelfish_user, 12345678

With this kind of configuration, I can get the following query to return content:

     select * from openquery(BFISH, 'select * from audit.test_table')

However, I cannot get the linked server syntax to work, and I've tried a bunch of different variations:

     select * from BFISH.audit.test_table
     select * from BFISH.babelfish_db.audit.test_table
     select * from BFISH.[master].audit.test_table
     select * from BFISH.[master].[master_audit].[test_table]
     select * from BFISH.[master_audit].test_table
     select * from BFISH.[babelfish_db].[master_audit].[test_table]

Now, I get back some error messages like it thinks it's getting through:

    Msg 7314, Level 16, State 1, Line 12
    The OLE DB provider "MSDASQL" for linked server "BFISH" does not contain the table ""babelfish_db"."master_audit"."test_table"". The table either does not exist or the current user does not have permissions on that table.

I've applied every permission I can think of to that test_table object:

![image](https://user-images.githubusercontent.com/567028/188014782-810c48df-c8f3-467d-8c99-a08462d1096c.png)

So it seems like it's close, but I can't seem to get over the last hill.

**Comment by robverschoor** [comment]
Babelfish does not yet support linked servers. This is on the roadmap, although so far I think we have primarily looked at the outbound variation. We have not looked at the inbound variation that you are showing here so it is quite possible something needs a bit of work. Thanks for reminding!

**Comment by Sjetware** [comment]
Good to know it's eventually coming, but sad that I guess I can't try leveraging that to switch some stuff to Aurora. Back to the drawing board!
