### ISSUE TITLE
[Bug]: TDS Stream crash when selecting a N/VARCHAR(MAX) variable

### ISSUE THREAD

**Issue by gutosantos82** [babelfish-for-postgresql/babelfish_extensions#58]
### Contact Details

augusto@gemeos.org

### What happened?

Receiving a "SQL Error [08S01]: The TDS protocol stream is not valid." on the following code

```
DECLARE @variable VARCHAR(max) = '';
set @variable = 'a'
select @variable
```

Expected result:

```
@variable
a
```

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3manuek** [comment]
Executing the above code block twice this from a `tsql` client, I get the following error:

```
~ tsql -S ${BBF_IP} -p 1433 -U bbf -v master 
Password: 
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Changed database context to 'master'.
1> DECLARE @variable VARCHAR(max) = '';
2> set @variable = 'a'
3> select @variable
4> GO
@variable
(0 rows affected)
1> DECLARE @variable VARCHAR(max) = '';
2> set @variable = 'a'
3> select @variable
4> GO
Error 20006 (severity 9):
        Write to the server failed
tds_submit_query() failed
```

Also, all executed commands after the error, even after attempting to `use master` to reconnect -- but this, could be specific to the tsql client.

**Comment by robverschoor** [comment]
When executing this code with 'sqlcmd' , it works correctly.

**Comment by nasbyj** [comment]
@3manuek or @gutosantos82, can you try this with `sqlcmd` instead of `tsql` (which we currently don't formally support...)
