### ISSUE TITLE
[Bug]: SQL Error [33557097] [S0001]: missing FROM-clause entry for table "XX"

### ISSUE THREAD

**Issue by mrtnjcl** [babelfish-for-postgresql/babelfish_extensions#61]
### What happened?

When i try to run the following SQL query against the TDS endpoint i get an error.

#### Query (simplified)
`UPDATE tabs SET tabOrder = t2.rn
FROM tabs t1 
JOIN (SELECT tabId, ROW_NUMBER() OVER (ORDER BY tabOrder) AS rn FROM tabs t2 WHERE accountId = 1234) t2 ON t1.tabId = t2.tabId
WHERE t1.accountId = 1234`

#### Error
`SQL Error [33557097] [S0001]: missing FROM-clause entry for table "t2"`

When i run the same query against MSSQL2008 server, the query works just fine. It also works just fine when i run it against pgsql server directly. Is this incompatibility outlined in the T-SQL limitations document? 

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
This looks like a known issue in Babelfish. For a better diagnosis, please provide a full reproduction , including the table DDL.

**Comment by suprio-amzn** [comment]
There are many fixes in Babelfish for Aurora PostgreSQL 3.1 which got released recently. Please try with the new version.
