### ISSUE TITLE
"permission denied for table ..." when trying to select a table in master_db created from postgres

### ISSUE THREAD

**Issue by mssqlserver** [babelfish-for-postgresql/babelfish_extensions#62]
### What's the question?

Hi! I want to access my babelfish-database (single-db-mode) via T-SQL AND postgres:
I'm planning to use some applications that can only "talk" postgres while other application only "talk" T-SQL. 
Both should use the same server running babelfish.

My idea is to create tables or views from postgres in the master_dbo that can be used via T-SQL. This way a postgres-application can share data with a tsql-application and vice-versa.

This is working: I create a table via T-SQL and I'm able to select the table via postgres

**T-SQL (masterdb):**
create table test_tsql (idx int)

**postgres (public@babelfish_db):**
select * from master_dbo.test_tsql

But the other way I have a permission-problem (permission denied for table test_pg)

**postgres (public@babelfish_db):**
create table master_dbo.test_pg (id int)

**T-SQL (masterdb):**
select * from test_pg

I did everything regarding GRANT from postgres-side with no effect:

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA master_dbo TO babelfish_user;
GRANT ALL PRIVILEGES ON TABLE  master_dbo.test_pg to babelfish_user;

What am I doing wrong?
Thanks for your help!

BR,
Bob

### Relevant log output or information

```shell
Babelfish for PostgreSQL with SQL Server Compatibility - 12.0.2000.8
Nov  4 2021 19:18:41
Copyright (c) Amazon Web Services
PostgreSQL 13.4 on x86_64-pc-linux-musl



SQL Error [33557097] [S0001]: permission denied for table test_pg
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
The bigger issue here is how the T-SQL and PG side of Babelfish can (or not) interact.

But first, GRANT and REVOKE, as well as the T-SQL database principal ("DB user") concept are not currently implemented in Babelfish (this is on the roadmap). Generally, performing DDL in PG and expecting this to be reflected on the T-SQL Babelfish layer, is not supported. Babelfish works the other direction: what you can access through the TDS port with T-SQL, can identically be accessed through the PG port when using the same PG user to connect as used when connecting to the TDS port. The reverse is however not necessarily true. While performing DDL through PG may in some cases be reflected in T-SQL, this will not always work. But more importantly, this is not recommended and may not be compatible with future releases of Babelfish.

To build applications that are partly implemented in T-SQL and partly in PG/plSQL, and which are accessing the same tables, create all tables in T-SQL. These tables can then be accessed through a PG connection. Stored procedures and queries that will be executed through a PG connection should best be written in PL/pgSQL; Stored procedures and queries that will be executed through a TDS connection should be written in T-SQL.

**Comment by max-webster** [comment]
I'll close this issue, as the question is answered by the best practices guidelines from Rob.

**Comment by robverschoor** [comment]
Actually we need to point to an upcoming doc update about  interoperability between Babelfish and PG (once the doc is out)

**Comment by max-webster** [comment]
OK, let me leave open so as not to overlook adding the pointer later.

**Comment by suprio-amzn** [comment]
Detailed answer provided - please also review Interoperability guidance doc [https://babelfishpg.org/docs/usage/interoperability/](https://babelfishpg.org/docs/usage/interoperability/).
