### ISSUE TITLE
[Bug]: "mi" is not a recognized datediff option

### ISSUE THREAD

**Issue by netoax** [babelfish-for-postgresql/babelfish_extensions#627]
### What happened?

Hi,
I was trying to run the `datediff` function with the `MI` abbreviation for `minute`, [as it works on SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver16#arguments), but got this error:

```text
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 1
"mi" is not a recognized datediff option.
```

It works fine with the `N` abbreviation and we had to update our legacy codebase. However, I think it's still import to map this issue here.

### Version

BABEL_2_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
This is a known current shortcoming of Babelfish. The remedy is to change 'mi' to 'minute'. Recent versions of the Babelfish Compass tool will make this change for you if you use the '-rewrite' option.

**Comment by netoax** [comment]
> This is a known current shortcoming of Babelfish. The remedy is to change 'mi' to 'minute'. Recent versions of the Babelfish Compass tool will make this change for you if you use the '-rewrite' option.

Thanks!

**Comment by suprio-amzn** [comment]
@netoax: A fix should be available in the upcoming release.

**Comment by suprio-amzn** [comment]
@netoax: a fix for this issue is available is part of the commit (https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/d637ad81862a683f65cad1c51d22b1656cf085af).
