### ISSUE TITLE
[Bug]: param not defined when using `sp_executesql` procedure

### ISSUE THREAD

**Issue by netoax** [babelfish-for-postgresql/babelfish_extensions#658]
### What happened?

Hi,

I have an application written in Node.js that uses the library `mssql` and is trying to list employees using the `@employeeName` as a parameter. However, after investigations, I found the TDS library used by `mssql`, called `tedious`, [is using the stored procedure `sp_executesql` under the hood to execute my queries.](https://github.com/tediousjs/tedious/blob/5015634344cac9fa8cd03d59538aa6b3395fd460/src/connection.ts#L2521)

According to the documentation, `sp_executesql` isn't supported. Is that right? Because it's working fine without parameters:

```sql
DECLARE @SQLString NVARCHAR(500);
SET @SQLString =
     N'SELECT * FROM employee';
EXECUTE sp_executesql @SQLString;
```

The issue arises only when calling the procedure with parameters:

```sql
DECLARE @SQLString NVARCHAR(500);
DECLARE @paramDefinition NVARCHAR(500);

SET @SQLString =
     N'SELECT * FROM employee where name = @employeeName';
SET @paramDefinition = N'@employeeName varchar(50)';
EXECUTE sp_executesql @SQLString, @paramDefinition,
                       @employeeName = 'carlos';
```

Do you have a plan for supporting this procedure with params?

I will let my application code below:

```node
const sql = require('mssql')

const run = async () => {
        await sql.connect(<connection-string>)
        const request = new sql.Request()
        request.input('employeeName', sql.VarChar, 'carlos')
        request.query('select * from employee where name = @employeeName', (err, result) => {})
}
```

Error:

```bash
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 17
param "@employeeName" not defined
```

### Version

BABEL_2_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
Why do you think sp_executesql is not supported? It has been supported since Babelfish v.1.0.0.
The issue in your example has to do with case-sensitivity of the variable name used as parameter. This is a known issue. 
When you use all-lowercase, it works fine:

1> create table employee(name varchar(20), surname varchar(20))
2> insert employee values ('john', 'smith')
3> insert employee values ('carlos', 'sanchez')
4> go

(1 rows affected)
(1 rows affected)

1> DECLARE @SQLString NVARCHAR(500);
2> DECLARE @paramDefinition NVARCHAR(500);
3> SET @SQLString = N'SELECT * FROM employee where name = @employeeName';
4> SET @paramDefinition = N'@employeename varchar(50)';
5> EXECUTE sp_executesql @SQLString, @paramDefinition, @employeename = 'carlos';
6> go
`name                       surname   `
`-------------------- --------------------`
`carlos                      sanchez`

(1 rows affected)

**Comment by netoax** [comment]
> Why do you think sp_executesql is not supported? It has been supported since Babelfish v.1.0.0. The issue in your example has to do with case-sensitivity of the variable name used as parameter. This is a known issue. When you use all-lowercase, it works fine:
> 
> 1> create table employee(name varchar(20), surname varchar(20)) 2> insert employee values ('john', 'smith') 3> insert employee values ('carlos', 'sanchez') 4> go
> 
> (1 rows affected) (1 rows affected)
> 
> 1> DECLARE @SQLString NVARCHAR(500); 2> DECLARE @paramDefinition NVARCHAR(500); 3> SET @SQLString = N'SELECT * FROM employee where name = @employeeName'; 4> SET @paramDefinition = N'@employeename varchar(50)'; 5> EXECUTE sp_executesql @SQLString, @paramDefinition, @employeename = 'carlos'; 6> go `name surname ` `-------------------- --------------------` `carlos sanchez`
> 
> (1 rows affected)

I found this procedure in the list of unsupported ones here that's why I got confused: https://babelfishpg.org/docs/limitations/stored_procedure_limitations/#unsupported-stored-procedures

Is there any mention of the case sensitivity there?

Thanks for the answer, I will change the name to lowercase and test it again.

**Comment by robverschoor** [comment]
I see.... that is not correct. I'll get it corrected. 
The list of supported/unsupported features applies to what is (not) implemented according to the planning in the Babelfish project.  The uppercase/lowercase issue here is more like a bug, and bugs are not documented here.
