### ISSUE TITLE
[Bug]: NULLs in DATE(TIME)-Fields as default-values not working

### ISSUE THREAD

**Issue by mssqlserver** [babelfish-for-postgresql/babelfish_extensions#666]
### What happened?

Lets assume you have a table called TESTTABLE with 2 columns: 
TEST VARCHAR(255)
TESTDATE DATETIME DEFAULT NULL

Now I insert new rows without specifying a value for TESTDATE:
INSERT INTO TESTTABLE (TEST) VALUES ('HELLO!')

MSSQL would return a result if I do this select:
SELECT * from TESTTABLE WHERE TESTDATE IS NULL

BABELFISH does not return a result for the statement above - instead you get a result 
SELECT * from TESTTABLE WHERE TESTDATE='01.01.1900'

I created a workaround using a INSERT/UPDATE-Trigger setting TESTDATE=NULL where TESTDATE='01.01.1900'.
Is this a bug you can fix or am I doing something wrong?

Thanks!

BR,
Robert

 

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
This is a known issue; the fix is expected in the next release of Babelfish (v.2.2.0). Note that this fix applies to new inserts only, it will not affect existing NULL values in such columns.

**Comment by suprio-amzn** [comment]
Fixed in v2.2.0 release -- https://babelfishpg.org/docs/versions/babelfish-2-2-0.html.
