### ISSUE TITLE
[Bug]: sys.triggers not available

### ISSUE THREAD

**Issue by mssqlserver** [babelfish-for-postgresql/babelfish_extensions#676]
### What happened?

Hi!

I'm using BF 2.1.0. trying to call "select * from sys.triggers" getting the error relation "sys.triggers" does not exist
Is this feature not yet available? https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/350

If it is not yet implemented can I determine the triggers for babelfish-tables using PSQL?

Thank you!

BR,
Robert

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
sys.triggers will be supported in v.2.2.0

**Comment by suprio-amzn** [comment]
Available in 2.2.0 release -- https://babelfishpg.org/docs/versions/babelfish-2-2-0.html.
