### ISSUE TITLE
 Unable to connect with Bablefish PostgreSQL using sqlcmd

### ISSUE THREAD

**Issue by khanna43** [babelfish-for-postgresql/babelfish_extensions#69]
### Contact Details

khanna.43@gmail.com

### What's the question?

I am getting this below error while connecting to Babelfish postgreSQL database using sqlcmd. I am able to make connection with the database using pgsql. I tried connecting from SSMS also but is failing with error ( A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.) (.Net SqlClient Data Provider)) 

Not sure if there is any mistake in Setup **Any help is really appreciated in this regard.** 

 sqlcmd -S tcp:192.168.56.11,1433 -U babelfish_user
Password:
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection because an error was encountered during handshakes before login. Common causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maximum allowed connections) on the server..
**Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection due to prelogin failure.**
[root@Rhel7VM1 ~]#
[root@Rhel7VM1 ~]#

/postgres/bin/psql -h 192.168.56.11 -p 1433
psql (11.2, server 13.4 Babelfish for PostgreSQL)
WARNING: psql major version 11, server major version 13.
         Some psql features might not work.
Type "help" for help.

postgres=#

Also SQLCMD is working fine when making connection to MS SQL Server databsae running on Docker 

sqlcmd -S tcp:192.168.29.88,1433 -U SA
Password:
1>
2>
3>

Checked the telnet to the Db server and is showing the expected behavior as per documentation 
https://babelfishpg.org/docs/faq/troubleshooting/

telnet 192.168.56.11 1433
Trying 192.168.56.11...
Connected to 192.168.56.11.
Escape character is '^]'.

Connection closed by foreign host.
[root@Rhel7VM1 ~]#

--------------------------------------------
Below is Bablefish postgreSQL database is setup on Ubuntu Host 

postgres@sachin-VirtualBox1:~$ /usr/local/pgsql/bin/psql -p 1433
psql (13.4 Babelfish for PostgreSQL)
Type "help" for help.

postgres=# \l
                                      List of databases
   Name    |     Owner      | Encoding | Collate | Ctype |         Access privileges
-----------+----------------+----------+---------+-------+-----------------------------------
 demo      | babelfish_user | UTF8     | en_IN   | en_IN |
 postgres  | babelfish_user | UTF8     | en_IN   | en_IN | =Tc/babelfish_user               +
           |                |          |         |       | babelfish_user=CTc/babelfish_user+
           |                |          |         |       | sysadmin=C*T*c*/babelfish_user   +
           |                |          |         |       | master_dbo=CTc/sysadmin          +
           |                |          |         |       | tempdb_dbo=CTc/sysadmin
 template0 | postgres       | UTF8     | en_IN   | en_IN | =c/postgres                      +
           |                |          |         |       | postgres=CTc/postgres
 template1 | postgres       | UTF8     | en_IN   | en_IN | =c/postgres                      +
           |                |          |         |       | postgres=CTc/postgres
(4 rows)

postgres=# select * from pg_extensions;
ERROR:  relation "pg_extensions" does not exist
LINE 1: select * from pg_extensions;
                      ^
postgres=# select * from pg_extension;
  oid  |      extname       | extowner | extnamespace | extrelocatable | extversion |         extconfig         | extcondition
-------+--------------------+----------+--------------+----------------+------------+---------------------------+---------------
 13434 | plpgsql            |       10 |           11 | f              | 1.0        |                           |
 16386 | uuid-ossp          |       10 |         2200 | t              | 1.1        |                           |
 16397 | babelfishpg_common |       10 |         2200 | t              | 1.0.0      |                           |
 17608 | babelfishpg_tsql   |       10 |         2200 | t              | 1.0.0      | {18146,18178,18156,18187} | {"","","",""}
 18274 | babelfishpg_tds    |       10 |         2200 | t              | 1.0.0      |                           |
(5 rows)

**On every attempt to try to connect to the database we are getting this message in the database log.
 LOG:  invalid length of startup packet**

### Relevant log output or information

```shell
2022-01-28 14:13:23.784 IST [6268] LOG:  listening on IPv4 address "0.0.0.0", port 1433
2022-01-28 14:13:23.800 IST [6268] LOG:  listening on Unix socket "/tmp/.s.PGSQL.1433"
2022-01-28 14:13:23.804 IST [6268] LOG:  could not bind IPv4 address "0.0.0.0": Address already in use
2022-01-28 14:13:23.804 IST [6268] HINT:  Is another postmaster already running on port 1433? If not, wait a few seconds and retry.
2022-01-28 14:13:23.804 IST [6268] WARNING:  could not create listen socket for "0.0.0.0"
2022-01-28 14:13:23.804 IST [6268] WARNING:  could not create any TCP/IP sockets to accept TDS connections
2022-01-28 14:13:23.809 IST [6269] LOG:  database system was shut down at 2022-01-28 14:13:18 IST
2022-01-28 14:13:23.812 IST [6268] LOG:  database system is ready to accept connections
2022-01-28 14:13:32.105 IST [6276] LOG:  invalid length of startup packet
2022-01-28 14:16:10.747 IST [6289] LOG:  invalid length of startup packet
2022-01-28 14:21:47.115 IST [6342] LOG:  invalid length of startup packet
2022-01-28 14:22:00.390 IST [6344] LOG:  invalid length of startup packet
2022-01-28 15:03:46.699 IST [6664] LOG:  invalid length of startup packet
2022-01-28 15:06:55.528 IST [6684] LOG:  invalid length of startup packet
2022-01-28 16:56:35.703 IST [7511] LOG:  invalid length of startup packet
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3manuek** [comment]
Hi @khanna43 ,

I see that you are connecting using the IP address in the sqlcmd. 

```
2022-01-28 14:13:23.804 IST [6268] WARNING:  could not create listen socket for "0.0.0.0"
```

Could this be related to the `babelfish_tds.listen_adresses` setting? Set it to `*` for allowing that port to listen to through all the interfaces.

**Comment by max-webster** [comment]
I see the connection problem was solved in the similar issue https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/65. I'm closing this one as a duplicate.
