### ISSUE TITLE
Sybase (now SAP) ASE Support

### ISSUE THREAD

**Issue by neuffer** [babelfish-for-postgresql/babelfish_extensions#7]
Given how close the Microsoft SQL Server fork of the Sybase (now SAP) ASE is,
will we see support of Sybase ASE in Babelfish?

SAP has all but killed ASE, so I guess there would be a number of users eager to migrate their Sybase ASE based applications to Postgres.

**Comment by nasbyj** [comment]
Thanks for the idea @neuffer! Do you have an ASE application that you could try with Babelfish? I suspect that should "just work".

**Comment by yairlenga** [comment]
Hi. I've posted #26 - basically same question - but narrow scope. I will appreciate any feedback you can contribute. Will be happy to share what I've already found.

**Comment by nasbyj** [comment]
I'm going to close this for now. Please feel free to re-open with any additional info.
