### ISSUE TITLE
babelfishpg_tsql.escape_hatch_unique_constraint not allowing me to create a unique constraint on nullable column

### ISSUE THREAD

**Issue by univsocal** [babelfish-for-postgresql/babelfish_extensions#70]
attempting to migrate existing sql server db/app to postgres-babelfish

babelfishpg_tsql.escape_hatch_unique_constraint not allowing me to create a unique constraint on nullable column

set to "ignore" - and still getting message

SQL Error [33557097] [S0001]: Nullable UNIQUE constraint is not supported. Please use babelfishpg_tsql.escape_hatch_unique_constraint to ignore or add a NOT NULL constraint

**Comment by robverschoor** [comment]
Could you please post:

- the exact Babelfish release you're using (OK, that is 1.0.0 right now, but adding this point as best practice)
- the result of **sp_babelfish_configure 'escape_hatch_unique_constraint'**
- the exact DDL you are executing plus the error output

**Comment by univsocal** [comment]
i WAS able to get this to work by creating the escape hatch. for some reason, this was not initially working for me.  With babelfish-postgres --- I AM ABLE to create a  unique constraint on a NULLABLE column - if i first change the escape hatch from STRICT to igniore

EXECUTE sp_babelfish_configure 'escape_hatch_unique_constraint', 'ignore', 'server'

NOW the following DDL DOES work


ALTER TABLE [dbo].[NetWorks] ADD  CONSTRAINT [NetWorks_UK] UNIQUE NONCLUSTERED 
(	[NetworkName] ASC )

**Comment by univsocal** [comment]
babelfish version - Babelfish for Aurora Postgres with SQL Server Compatibility - 12.0.2000.8
Oct 13 2021 17:34:47
Copyright (c) Amazon Web Services
PostgreSQL 13.4 on aarch64-unknown-linux-gnu

**Comment by univsocal** [comment]
ORIGINAL message BEFORE escape hatch was  
SQL Error [33557097] [S0001]: Nullable UNIQUE constraint is not supported. Please 
use babelfishpg_tsql.escape_hatch_unique_constraint 
to ignore or add a NOT NULL constraint

**Comment by robverschoor** [comment]
This is expected: most Babelfish escape hatches are set to 'strict' out of the box.  
Thanks for confirming.
