### ISSUE TITLE
[Question]: Does Babelfish support a higher version than SQL Server 2014?

### ISSUE THREAD

**Issue by markusadelsberger** [babelfish-for-postgresql/babelfish_extensions#703]
Hi,

**What's your question?**
we're currently migrating an application of ours to AWS, using an Aurora Database with Babelfish with Postgres, our Application is a Spring Boot Application which connects via JDBC.

Our current problem is that Babelfish always reports that it is running SQL version 2014, but one of our libraries (Flyway) requires a higher version. We know we can overwrite the output of ``select @@version``, but Flyway uses the metadata of the JDBC driver, which in turn uses the output of ``SELECT SERVERPROPERTY('productversion')``, and this still reports version 2014.

Is there any way we can work around this issue?

If you're wondering why I didn't use the Question template, this is due to this bug -> https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/702

**Version**

BABEL_1_X_DEV (Default)

KR,

Markus

**Comment by robverschoor** [comment]
There is currently no way to let Babelfish return a different SQL Server version, but we have noted the requirement for making this configurable.

**Comment by markusadelsberger** [comment]
Hi Rob,
thanks for the info, consider the question answered, I'll close it.
We'll have to go with a native SQL server then.
KR,
Markus
