### ISSUE TITLE
[Question]: operator does not exist: sys.uniqueidentifier = unknown

### ISSUE THREAD

**Issue by KevinDJones** [babelfish-for-postgresql/babelfish_extensions#704]
### What happened?

I'm using babelfish with AWS Postgres Aurora and everything is working well. I would, however, like to query the babelfish data inside of Postgres. I'm able to do that just fine for most data types, but not custom babelfish ones like uniqueidentifier. 

`Select * from table where id = 4` works. `Select * from table where id = '327A3F50-1826-4CFF-96C1-00055ACEB534'` gives the error `operator does not exist: sys.uniqueidentifier = unknown`

This really limits what I can do with my migrated SQL Server data inside of Postgres, especially for a db that is mainly Guid based. I can't seem to create any casts for sys.uniqueidentifier because I don't own it. Is there any way around this?

### Version

BABEL_1_X_DEV (Default)

### Which flavor of Linux are you using when you see the bug?

Amazon Linux

### Relevant log output

```shell
ERROR:  operator does not exist: sys.uniqueidentifier = unknown
LINE 1: ...ect * from table where id = '327A3F50-1826-4CFF-96C1-00055ACEB534'
                                     ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
SQL state: 42883
Character: 57
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by 2jungkook** [comment]
@KevinDJones
1. what is the data type of `id` column?
2. Which Babelfish version you are using? (You can check this by `select cast(serverproperty('BabelfishVersion') as varchar(10)) babelfish_version;`)

**Comment by KevinDJones** [comment]
@2jungkook The `id` column is of type `sys.uniqueidentifier`. Babelfish version is `2.1.2`.

**Comment by 2jungkook** [comment]
I think you are trying to use `sys.uniqueidentifier` data type in PG connection instead of TDS connection, right?

**Comment by KevinDJones** [comment]
@2jungkook That's correct. Everything works fine from a TDS connection. I understand that writing queries with a PG connection against babelfish-created tables isn't necessarily the primary use case here, I'm just trying to see if there's any way to do it.

I have found that by converting both sides of the statements to a normal pg type it will work:
```
select * from table where cast(id as varchar) = cast('327A3F50-1826-4CFF-96C1-00055ACEB534' as varchar)
```

But that's not ideal. I have a couple use cases where this would be helpful:

1. Let's say I have legacy data in tables in the babelfish database (`babelfish_db`), but new functionality would just go to regular Postgres (`postgres`). It would be nice to be able to join tables. I can do that with integers keys, but not with Guids because of this.
2. AWS DMS (Database Migration Service) officially doesn't support Babelfish, but it does support Postgres. It works perfectly with integer based PKs, but again, not with Guid based because of this.

I'm in AWS and therefore don't have control of `sys.uniqueidentifier`. If I did, I would create explicit casts and this would all just work (with potential unforeseen consequences I'm sure)

**Comment by 2jungkook** [comment]
Most operators are under `sys` namespace, e.g., https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/BABEL_2_X_DEV/contrib/babelfishpg_common/sql/uniqueidentifier.sql#L82. Hence, adding `sys` to your `search_path` would work, e.g.,
```
create table t1 (a sys.uniqueidentifier);
select * from t1 where a = '327A3F50-1826-4CFF-96C1-00055ACEB534'; -- error
set search_path to sys, pg_catalog, public;
select * from t1 where a = '327A3F50-1826-4CFF-96C1-00055ACEB534'; -- works!
```
