### ISSUE TITLE
unrecognized configuration parameter: NO_BROWSETABLE

### ISSUE THREAD

**Issue by mssqlserver** [babelfish-for-postgresql/babelfish_extensions#71]
### What happened?

Hi,

many SQL-Query-Analyzers execute "SET NO_BROWSETABLE ON" or "SET NO_BROWSETABLE OFF" when accessing data or opening a connection.

Unfortunatelly this feature is not supported which makes those tools useless.
I was able to get a Query-Analyzer (FlySpeedSQL-Query) on windows working using a ODBC-connection.

Is there a way that this command does not fire an error (just ignoring the command)?

Thank you!

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
The Babelfish project aims to provide T-SQL support for end user applications. For activities such as query analysis, monitoring, backups, etc. the direction is to perform such activities from the PostgreSQL side, using PG tools and utilities, since we are running on PG after all, and the internals will be PG-specific. 

That said, could you please elaborate on the use case for using query analyzer tools against Babelfish? Keep in mind that query plans for Babelfish queries will be PG plans, not T-SQL plans.

**Comment by mssqlserver** [comment]
Well, as a developer a Query-Analyzer is my all-day-tool I'm using for development.

When trying to implement babelfish (means that babelfish will become the primary database for my application) I need to run TSQL-queries against babelfish in order to develop my application - this is when such a tool is needed.

I know that I can access my TSQL-Tables using postgreSQL, but my application only "talks" TSQL - this is why I need a way to access the database for debugging purposes like my software does.

![flyspeed](https://user-images.githubusercontent.com/56147661/152801677-2caa1a5f-72fa-49e3-b273-8679a4e761a3.png)

**Comment by robverschoor** [comment]
Given that query plans and internal tech details will not be looking like they do on SQL Server (but rather, will be PG-like) exactly what are you expecting to work in Babelfish from this perspective?  It would be helpful to have some examples in terms of actual queries being issued by your tools, and expected results.  
BTW, note that FOR BROWSE is not currently supported in Babelfish.

**Comment by mssqlserver** [comment]
I'm only interested in inspecting tables, queries and stored procedures / functions.
These are the most common used objects when coding standard software (from my perspective).

To me it is important to see the database exact the same way as my application which is connecting via TSQL to the postgres-database.

So it would be great if babelfish would accept the "SET NO_BROWSETABLE" command without doing anything so that most of these query tools work with a standard MSSQL-Connection (ADO for example).

At the moment I have to use ODBC with "ODBC DRIVER 17 for SQL Server" to get (some) of these query-tools work. It seems that connecting with ODBC "in some cases" does not fire the "SET NO_BROWSETABLE" table - what makes it work.

**Comment by nasbyj** [comment]
@rcv-aws it's sounding like we should add an escape hatch for `SET NO_BROWSETABLE`, do you agree?

**Comment by robverschoor** [comment]
Not currently. We are tracking this feature request internally.

**Comment by alexklochkov** [comment]
Hi,

We have the same problem in our application using ADO.Recordset connected to BF via SQLOLEDB provider.

ADO adds SET NO_BROWSETABLE to every SELECT query, and we cannot turn this option off.

**Comment by mssqlserver** [comment]
I am glad that I‘m not the only one having this problem. 

Do you see a chance to simply ignore all SET NO_BROWSETABLE that are sent to BF?

**Comment by williamgosse** [comment]
I"ve seen this same issue with an older desktop app I'm that uses the native ms sqlclient.  This set is issued on every select statement made.  Note I'm using babelfish 1.1.0 with AWS Aurora Postgres 13.5

**Comment by robverschoor** [comment]
We are looking to put this under a Babelfish escape hatch, just like some other unsupported session-level settings.

**Comment by williamgosse** [comment]
That sounds great. Any estimate on when we can see this in AWS?

**Comment by robverschoor** [comment]
The release vehicle has not been identified yet

**Comment by mssqlserver** [comment]
Hi! Are there news about this issue?

**Comment by mssqlserver** [comment]
Hi,
sorry for asking again, but do you have news about this issue? Is there a chance to modify the code so I can control / extend the escape hatches by myself? 

Perhaps it would be a good idea to create a config-file that users can edit in order to add escape hatches by themselves?

Thank you for your support.

**Comment by robverschoor** [comment]
This feature is currently being worked on and will hopefully be available in the next Babelfish release

**Comment by suprio-amzn** [comment]
This is now fixed (https://babelfishpg.org/docs/versions/babelfish-2-2-0.html#changes).
