### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by bradtx19** [babelfish-for-postgresql/babelfish_extensions#73]
### Contact Details

bthomas@paymerang.com

### What's the question?

The T-SQL stored procedures that I wish to execute using babelfish do not fully qualify the names of the tables with the name of the schema.  As a result I get the 'relation "x" does not exist' error.   If I edit my procedure and qualify the table names with the schema name then this error goes away.  If I look at the search_path with pgAdmin I see that my schema is the first in the list followed by public and the $user.  But that is on a postgres connection - not  the TDS connection.  

How can I use unqualified table names in my stored procedures?

Specifically I connected to Babelfish-enabled Postgres cluster using SSMS.  Next I created a database named 'demo' and within 'demo' I created a schema named 'biz'.   I created all of my tables and stored procedures in the 'biz' schema.  

Is there something like the postgre search_path that I can set in the babelfish TDS connection?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
Could you please provide a concrete example of how you are creating the object, and how you are referencing it?

**Comment by bradtx19** [comment]
For example:
After creating a Babelfish enabled Postgres cluster I executed these statements in SSMS:

    create database demo
    use demo
    create schema biz
    create table [biz].[cities](
	    [city] varchar(128),
	    [state] varchar(128)
	    )

    create procedure [biz].[p_getcities] as
    begin
	    select * from cities
    end

    insert into [biz].[cities](city, state) values ('Portland', 'OR')
    insert into [biz].[cities](city, state) values ('Richmond', 'VA')

    exec [biz].p_getcities

And I get this error message after running p_getcities:

Msg 33557097, Level 16, State 1, Line 21
relation "cities" does not exist

When I switch to pgAdmin and try to run the stored procedure like this:

    CALL biz.p_getcities()

I get a similar error:

ERROR:  relation "cities" does not exist
LINE 1: select * from cities
                      ^
QUERY:  select * from cities
CONTEXT:  PL/tsql function biz.p_getcities() line 2 at SQL statement
SQL state: 42P01

However, when I set the search_path like this:

    set search_path to biz

And the execute the stored procedure I get the expected results:

Portland        OR
Richmond        VA

Is there an equivalent to search_path in Babelfish?

**Comment by robverschoor** [comment]
What is happening here is that the name resolution inside the procedure biz.p_getcities does not correctly resolve the table name. It resolves it to 'dbo' schema while it should resolve it to 'biz' schema. As you noted, this is related to the search_path setting, and this is not set correctly in this case. 
This is a known bug and we hope to fix it soon.

Until then, the workaround is to qualify the table name with the schema name, i.e. **select * from biz.cities**

**Comment by bradtx19** [comment]
Thank you for the explanation.  Here's hoping the bug is fixed soon.
