### ISSUE TITLE
[Question]: Uanble to compile babelfishpg_money

### ISSUE THREAD

**Issue by voha-ov** [babelfish-for-postgresql/babelfish_extensions#74]
### Contact Details

kacnepb@gmail.com

### What's the question?

Hi guys. I am trying to install babelfish extensions and I encountered with the problems like this:

voli@voli-VirtualBox:~/bf_ext/babelfish_extensions/contrib/babelfishpg_money$ sudo make
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
make: --pgxs: No such file or directory
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
make: *** No rule to make target '/fixeddecimal--1.1.0_base.sql', needed by 'babelfishpg_money--1.1.0.sql'.  Stop.

Can someone help me with this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thephantomthief** [comment]
Hi @voha-ov, did you set the `PG_CONFIG` environment variable? Could you try setting it and retry compiling the extension? You can find instructions to set it under the "Set environment variables and paths" section in the [build instructions](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/BABEL_1_X_DEV/contrib/README.md)

**Comment by suprio-amzn** [comment]
@voha-ov: Was your issue resolved after following the build instructions? Do you require further help?

**Comment by suprio-amzn** [comment]
Please reopen or file a new issue if you are still facing problems.
