### ISSUE TITLE
[Bug]: MSSQL ODBC wizard doesn't let you select a database

### ISSUE THREAD

**Issue by palmerj** [babelfish-for-postgresql/babelfish_extensions#80]
### Contact Details

jpalmer@linz.govt.nz

### What happened?

I've create a single-db bablefish cluster with one user database. When I use the Windows Create New Data Soruce ODBC connection for MSSQL I can connect, however I can't see the user database in the dropdown list, nor can I test datasource. 

<img width="505" alt="create odbc list database" src="https://user-images.githubusercontent.com/580022/155272216-711559a5-fdeb-4751-8f1e-b72867ee0574.png">

The list databases does work because the following query fails:

```
2022-02-23 06:44:41.561 UTC [4099] ERROR:  Cross DB query is not supported
2022-02-23 06:44:41.561 UTC [4099] CONTEXT:  SQL statement "select name from master.dbo.sysdatabases where has_dbaccess(name)=1"
```

I also note that has_dbaccess function won't ever work in my situation as my PostgreSQL database name doesn't match the MSSQL user database name, and has_dbaccess uses the PG function `has_database_privilege` with MSSQL database name as the database name.

<img width="363" alt="create odbc test" src="https://user-images.githubusercontent.com/580022/155272225-291e7240-f48f-4e81-9dc5-46a2761a5a15.png">

The test doesn't also work because it tries to run the following CrossDB query:

```sql
"select name from master.dbo.syscharsets where id = convert(tinyint, databasepropertyex ( db_name() , 'sqlcharset'))"
```

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
It appears this problem happens with older ODBC versions, like ODBC Driver version 10.0. When using a recent ODBC driver version (like version 17), the connection works fine, so that is the recommended workaround for now.

**Comment by suprio-amzn** [comment]
@palmerj : Were you able to solve this problem by upgrading the ODBC Driver version?
