### ISSUE TITLE
[Bug]: sys.smalldatetime(0) without time zone is invalid syntax

### ISSUE THREAD

**Issue by martwana** [babelfish-for-postgresql/babelfish_extensions#838]
### What happened?

If this bug report is in the wrong repository, please let me know where it should be. I'm also using Babelfish 2.1.1 locally. 

I'm working to provide a working local environment in addition to using Babelfish/Postgres on AWS. 

I'm trying to validate the use of `pg_dump` and `pg_restore` and running into issues with the SQL generated by `pg_dump`

An example query is below, the table name has been changed and constraints removed. It fails to create the table specifically due to the `without time zone` part of the data columns SQL. Removing `without time zone` allow the query to run without error. 

Has anyone seen this before?

```
CREATE TABLE IF NOT EXISTS mmreburatest
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    name sys."varchar"(200) COLLATE sys.bbf_unicode_cp1_ci_as,
    description sys."varchar"(255) COLLATE sys.bbf_unicode_cp1_ci_as,
    status sys."bit" NOT NULL,
    createddate sys.smalldatetime(0) without time zone NOT NULL DEFAULT sys.getdate(),
    createdbyid sys.nvarchar(128) COLLATE sys.bbf_unicode_cp1_ci_as,
    lastupdated sys.smalldatetime(0) without time zone,
    lastupdatedbyid sys.nvarchar(128) COLLATE sys.bbf_unicode_cp1_ci_as,
    identifier sys.uniqueidentifier NOT NULL DEFAULT sys.newid(),
    tenantid integer DEFAULT 1
)
```

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_common

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default), Other

### Relevant log output

```shell
ERROR:  syntax error at or near "without"
LINE 7:     createddate sys.smalldatetime(0) without time zone NOT N...
                                             ^
SQL state: 42601
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by suprio-amzn** [comment]
@martwana : We have not documented the use of `pg_dump` and `pg_restore` for Babelfish. Please let us know what you are trying to validate.

**Comment by martwana** [comment]
@suprio-amzn I'm trying to validate that it's possible to take a backup from a running babelfish database and restore it correctly to another one. Standard backup/restore process, which so far does not work. 

I'm using `pg_dump` and `pg_restore` as the babelfish documentation specifically says we should use native postgres backup/restore tools. 

It raises major concerns that we're unable to restore from a database backup. 

EDIT: I'd also stress that given I'm using native tools and software that is unmodified, this issue should continue to be marked as a bug.

**Comment by sksql** [comment]
With regards to the create table in the question, this is not valid T-SQL. For this to be valid T-SQL:
- Replace "CREATE TABLE IF NOT EXISTS" with "CREATE TABLE:
- Replace "GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 )" with "IDENTITY ( 0, 1 )"
- Replace "smalldatetime(0) without time zone" with "smalldatetime".

With the above changes, MSSQL still objects to identifiers (e.g. collation bbf_unicode_cp1_ci_as is not available in MSSQL).
By 1) removing schema qualifier from collations and 2) setting QUOTED_IDENTIFIER to ON, it now runs fine in Babelfish. So, regarding the question regarding the query, the remaining question is about qualifying collations with schema.
```
SET QUOTED_IDENTIFIER ON
go
CREATE TABLE mmreburatest
(
    id integer NOT NULL IDENTITY ( 0, 1 ),
    name sys."varchar"(200) COLLATE bbf_unicode_cp1_ci_as,
    description sys."varchar"(255) COLLATE bbf_unicode_cp1_ci_as,
    status sys."bit" NOT NULL,
    createddate sys.smalldatetime NOT NULL DEFAULT sys.getdate(),
    createdbyid sys.nvarchar(128) COLLATE bbf_unicode_cp1_ci_as,
    lastupdated sys.smalldatetime,
    lastupdatedbyid sys.nvarchar(128) COLLATE bbf_unicode_cp1_ci_as,
    identifier sys.uniqueidentifier NOT NULL DEFAULT sys.newid(),
    tenantid integer DEFAULT 1
)
go
SELECT * FROM mmreburatest
go
id          name                                                                                                                                                                                                     description                                                                                                                                                                                                                                                     status createddate         createdbyid                                                                                                                      lastupdated         lastupdatedbyid                                                                                                                  identifier                           tenantid
----------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ------ ------------------- -------------------------------------------------------------------------------------------------------------------------------- ------------------- -------------------------------------------------------------------------------------------------------------------------------- ------------------------------------ -----------

(0 rows affected)
```

**Comment by sksql** [comment]
With regards to the SQL, it does is not runnable on PostgreSQL. As stated in the question, the clause "without time zone" is invalid. A workaround would be to edit the CREATE TABLE statement and manually delete this clause. Then it runs merrily through my psql/PG (14.4)

**Comment by suprio-amzn** [comment]
> _@martwana : We have not documented the use of `pg_dump` and `pg_restore` for Babelfish. Please let us know what you are trying to validate._

We are currently not supporting backup restore using native `pg_dump` and `pg_restore` tools.
