### ISSUE TITLE
[Bug]: MSOLEDBSQL.1 Write is normal, read fails, and TCP communication message is recorded

### ISSUE THREAD

**Issue by gaoxy2006git** [babelfish-for-postgresql/babelfish_extensions#853]
### What happened?

read fails
14:48:30 TRN -->> 127.0.0.1:49722 <188> ......................................&.....p......p.s.e.l.e.c.t. .*. .f.r.o.m. .s.t.u.d.e.n.t. .w.h.e.r.e. .S.T.U.
.N.U.M.=.'.6.'. .a.n.d. .S.T.U._.N.A.M.E.=.'.6.'...&........&........&..
[03 01 00 BC 00 00 01 00 16 00 00 00 12 00 00 00 02 00 00 00 00 00 00 00 00 00 01 00 00 00 FF FF 02 00 00 00 00 01 26 04 00 00 00 E7 70 00 04 08 D0 00 00 7
 00 73 00 65 00 6C 00 65 00 63 00 74 00 20 00 2A 00 20 00 66 00 72 00 6F 00 6D 00 20 00 73 00 74 00 75 00 64 00 65 00 6E 00 74 00 20 00 77 00 68 00 65 00
72 00 65 00 20 00 53 00 54 00 55 00 5F 00 4E 00 55 00 4D 00 3D 00 27 00 36 00 27 00 20 00 61 00 6E 00 64 00 20 00 53 00 54 00 55 00 5F 00 4E 00 41 00 4D 00
45 00 3D 00 27 00 36 00 27 00 00 01 26 04 04 02 80 03 00 00 01 26 04 04 04 80 04 00 00 01 26 04 00 ]

14:48:30 TRN <<-- 127.0.0.1:49722 <128> .........h.i.....$.o.n.l.y. .R.E.A.D. .O.N.L.Y. .c.u.r.s.o.r.s. .a.r.e. .s.u.p.p.o.r.t.e.d..B.A.B.E.L.F.I.S.H......
............
[04 01 00 80 00 00 00 00 AA 68 00 69 0A 00 02 01 10 24 00 6F 00 6E 00 6C 00 79 00 20 00 52 00 45 00 41 00 44 00 20 00 4F 00 4E 00 4C 00 59 00 20 00 63 00 7
 00 72 00 73 00 6F 00 72 00 73 00 20 00 61 00 72 00 65 00 20 00 73 00 75 00 70 00 70 00 6F 00 72 00 74 00 65 00 64 00 09 42 00 41 00 42 00 45 00 4C 00 46
00 49 00 53 00 48 00 00 01 00 00 00 FE 02 00 02 00 00 00 00 00 00 00 00 00 ]

Write is normal,
14:48:23 TRN -->> 127.0.0.1:49722 <300> ...,..........................i.n.s.e.r.t. .i.n.t.o. .s.t.u.d.e.n.t. .(.S.T.U._.N.U.M.,.S.T.U._.N.A.M.E.,.S.T.U._.C
H.I.N.E.S.E.,.S.T.U._.M.A.T.H.S.,.S.T.U._.E.N.G.L.I.S.H.,.S.T.U._.P.H.Y.S.I.C.S.,.S.T.U._.C.H.E.M.I.S.T.R.Y.). .v.a.l.u.e.s. .(.'.6.'.,.'.6.'.,.'.6.'.,.'.
.'.,.'.6.'.,.'.6.'.,.'.6.'.).
[01 01 01 2C 00 00 01 00 16 00 00 00 12 00 00 00 02 00 00 00 00 00 00 00 00 00 01 00 00 00 69 00 6E 00 73 00 65 00 72 00 74 00 20 00 69 00 6E 00 74 00 6F 0
 20 00 73 00 74 00 75 00 64 00 65 00 6E 00 74 00 20 00 28 00 53 00 54 00 55 00 5F 00 4E 00 55 00 4D 00 2C 00 53 00 54 00 55 00 5F 00 4E 00 41 00 4D 00 45
00 2C 00 53 00 54 00 55 00 5F 00 43 00 48 00 49 00 4E 00 45 00 53 00 45 00 2C 00 53 00 54 00 55 00 5F 00 4D 00 41 00 54 00 48 00 53 00 2C 00 53 00 54 00 55
00 5F 00 45 00 4E 00 47 00 4C 00 49 00 53 00 48 00 2C 00 53 00 54 00 55 00 5F 00 50 00 48 00 59 00 53 00 49 00 43 00 53 00 2C 00 53 00 54 00 55 00 5F 00 43
00 48 00 45 00 4D 00 49 00 53 00 54 00 52 00 59 00 29 00 20 00 76 00 61 00 6C 00 75 00 65 00 73 00 20 00 28 00 27 00 36 00 27 00 2C 00 27 00 36 00 27 00 2C
00 27 00 36 00 27 00 2C 00 27 00 36 00 27 00 2C 00 27 00 36 00 27 00 2C 00 27 00 36 00 27 00 2C 00 27 00 36 00 27 00 29 00 ]

14:48:24 TRN <<-- 127.0.0.1:49722 <21> .....................
[04 01 00 15 00 00 00 00 FD 10 00 C3 00 01 00 00 00 00 00 00 00 ]

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tds

### Which flavor of Linux are you using when you see the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by gaoxy2006git** [comment]
Open("Provider=MSOLEDBSQL.1;Data Source=127.0.0.1;Initial Catalog=master;User Id=babelfish_user;Password=12345678;","","",adModeUnknown);

**Comment by gaoxy2006git** [comment]
select * from student where STU_NUM='6' and STU_NAME='6';

**Comment by gaoxy2006git** [comment]
Provider=MSOLEDBSQL.1; and Provider=SQLOLEDB.1 Login is normal, write is normal, read failed.

Driver={SQL Server};Login failed, but it is normal in MSSQL

ADO operation under VC 6.0

**Comment by gaoxy2006git** [comment]
isqlw. exe login prompt: master_ Dbo.syscharsets does not exist！

**Comment by gaoxy2006git** [comment]
Babelfish for PostgreSQL with SQL Server Compatibility - 12.0.2000.8
PostgreSQL 13.7 on x86_64-pc-linux-gnu

**Comment by gaoxy2006git** [comment]
VC program running environment is wine 7.0。

**Comment by gaoxy2006git** [comment]
How to create master.dbo.syscharsets?

**Comment by robverschoor** [comment]
Which Babelfish version is this? Please provide the output of `SELECT CAST(SERVERPROPERTY('BabelfishVersion') AS VARCHAR)`

**Comment by gaoxy2006git** [comment]
serverproperty                
------------------------------
1.3.2

**Comment by robverschoor** [comment]
In Babelfish, you can run this:
`create view dbo.syscharsets as select * from sys.syscharsets`

**Comment by gaoxy2006git** [comment]
SQL Server Query Analyzer can log in normally.

**Comment by gaoxy2006git** [comment]
but run "SELECT @@VERSION"
out=
version                                                                                                                                                                                                                                                          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 


[Microsoft][ODBC SQL Server Driver]收到来自 SQL Server 的未知令牌

**Comment by gaoxy2006git** [comment]
VC programming ADO accesses MSSQL and runs relevant TCP messages of "select * from student where STU_NUM='0 'and STU_NAME='0'"
22:55:12 TRN -->> 192.168.10.110:57192 <166> ................&.....p......p.s.e.l.e.c.t. .*. .f.r.o.m. .s.t.u.d.e.n.t. .w.h.e.r.e. .S.T.U._.N.U.M.=.'.0.'.
.a.n.d. .S.T.U._.N.A.M.E.=.'.0.'...&........&........&..
[03 01 00 A6 00 00 01 00 FF FF 02 00 00 00 00 01 26 04 00 00 00 E7 70 00 09 04 00 01 C6 70 00 73 00 65 00 6C 00 65 00 63 00 74 00 20 00 2A 00 20 00 66 00
72 00 6F 00 6D 00 20 00 73 00 74 00 75 00 64 00 65 00 6E 00 74 00 20 00 77 00 68 00 65 00 72 00 65 00 20 00 53 00 54 00 55 00 5F 00 4E 00 55 00 4D 00 3D 0
 27 00 30 00 27 00 20 00 61 00 6E 00 64 00 20 00 53 00 54 00 55 00 5F 00 4E 00 41 00 4D 00 45 00 3D 00 27 00 30 00 27 00 00 01 26 04 04 02 80 03 00 00 01
26 04 04 04 80 04 00 00 01 26 04 00 ]

22:55:12 TRN <<-- 192.168.10.110:57192 <396> .....4..................S.T.U._.N.U.M..............S.T.U._.N.A.M.E..............S.T.U._.C.H.I.N.E.S.E........
.....S.T.U._.M.A.T.H.S..............S.T.U._.E.N.G.L.I.S.H..............S.T.U._.P.H.Y.S.I.C.S..............S.T.U._.C.H.E.M.I.S.T.R.Y.....8.R.O.W.S.T.A.T..
....s.t.u.d.e.n.t.....................................y.............&...............&...............&...............&...............
[04 01 01 8C 00 34 01 00 81 08 00 00 00 09 00 EF 10 00 04 08 D0 00 00 07 53 00 54 00 55 00 5F 00 4E 00 55 00 4D 00 00 00 09 00 EF 10 00 04 08 D0 00 00 08
53 00 54 00 55 00 5F 00 4E 00 41 00 4D 00 45 00 00 00 09 00 EF 10 00 04 08 D0 00 00 0B 53 00 54 00 55 00 5F 00 43 00 48 00 49 00 4E 00 45 00 53 00 45 00 0
 00 09 00 EF 10 00 04 08 D0 00 00 09 53 00 54 00 55 00 5F 00 4D 00 41 00 54 00 48 00 53 00 00 00 09 00 EF 10 00 04 08 D0 00 00 0B 53 00 54 00 55 00 5F 00
45 00 4E 00 47 00 4C 00 49 00 53 00 48 00 00 00 09 00 EF 10 00 04 08 D0 00 00 0B 53 00 54 00 55 00 5F 00 50 00 48 00 59 00 53 00 49 00 43 00 53 00 00 00 0
 00 EF 10 00 04 08 D0 00 00 0D 53 00 54 00 55 00 5F 00 43 00 48 00 45 00 4D 00 49 00 53 00 54 00 52 00 59 00 00 00 00 00 38 07 52 00 4F 00 57 00 53 00 54
00 41 00 54 00 A4 11 00 01 07 00 73 00 74 00 75 00 64 00 65 00 6E 00 74 00 A5 18 00 01 01 00 02 01 00 03 01 00 04 01 00 05 01 00 06 01 00 07 01 00 08 00 1
 FF 11 00 C1 00 00 00 00 00 79 00 00 00 00 AC 0D 00 00 01 00 00 00 00 26 04 04 F3 DE BC 0A AC 0D 00 00 01 00 00 00 00 26 04 04 02 00 00 00 AC 0D 00 00 01
00 00 00 00 26 04 04 04 00 00 00 AC 0D 00 00 01 00 00 00 00 26 04 04 FF FF FF FF FE 00 00 E0 00 00 00 00 00 ]

22:55:12 TRN -->> 192.168.10.110:57192 <50> ...2............&........&.. .....&........&......
[03 01 00 32 00 00 01 00 FF FF 07 00 02 00 00 00 26 04 04 F3 DE BC 0A 00 00 26 04 04 20 00 00 00 00 00 26 04 04 01 00 00 00 00 00 26 04 04 01 00 00 00 ]

22:55:12 TRN <<-- 192.168.10.110:57192 <165> .....4........0. . . . . . . ...0. . . . . . . ...0. . . . . . . ...0. . . . . . . ...0. . . . . . . ...0. .
. . . . . ...0. . . . . . . ..............y.............
[04 01 00 A5 00 34 01 00 81 FF FF D1 10 00 30 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 10 00 30 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 10 00 30
00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 10 00 30 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 10 00 30 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 1
 00 30 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 10 00 30 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 01 00 00 00 FF 11 00 C1 00 01 00 00 00 79 00 00
00 00 FE 00 00 E0 00 00 00 00 00 ]

22:55:12 TRN -->> 192.168.10.110:57192 <50> ...2............&........&.. .....&........&......
[03 01 00 32 00 00 01 00 FF FF 07 00 02 00 00 00 26 04 04 F3 DE BC 0A 00 00 26 04 04 20 00 00 00 00 00 26 04 04 01 00 00 00 00 00 26 04 04 01 00 00 00 ]

22:55:12 TRN <<-- 192.168.10.110:57192 <34> ...".4..............y.............
[04 01 00 22 00 34 01 00 81 FF FF FF 11 00 C1 00 00 00 00 00 79 00 00 00 00 FE 00 00 E0 00 00 00 00 00 ]

**Comment by gaoxy2006git** [comment]
How do I configure or modify Babelfish to be compatible with MSSQL?

**Comment by gaoxy2006git** [comment]
select * from dbo.sysdatabases;and select * from master.dbo.sysdatabases; Run OK.

**Comment by robverschoor** [comment]
> How do I configure or modify Babelfish to be compatible with MSSQL?

Babelfish is doing exactly that. But as you can see we don't have exact 100% compatibility. For the sysXXX catalogs that are not existing in dbo but only in sys, you can create a view as I showed in my earlier response. Other than that, we are continuously working to extend the coverage of Babelfish. You may want to go to the recently-released v.2.2.0 (on PG 14.5) which supports significantly more T-SQL features than your 1.3.x version (though I think the issues you mentioned above will exist there too)

**Comment by gaoxy2006git** [comment]
I have installed 1.3.2.How do I upgrade to 2.2.0?



---Original---
From: "Rob ***@***.***&gt;
Date: Thu, Nov 17, 2022 16:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [babelfish-for-postgresql/babelfish_extensions] [Bug]:MSOLEDBSQL.1 Write is normal, read fails, and TCP communication message isrecorded (Issue #853)




  
How do I configure or modify Babelfish to be compatible with MSSQL?
  
Babelfish is doing exactly that. But as you can see we don't have exact 100% compatibility. For the sysXXX catalogs that are not existing in dbo but only in sys, you can create a view as I showed in my earlier response. Other than that, we are continuously working to extend the coverage of Babelfish. You may want to go to the recently-released v.2.2.0 (on PG 14.5) which supports significantly more T-SQL features than your 1.3.x version (though I think the issues you mentioned above will exist there too)

**Comment by kuntalghosh** [comment]
The log mentioned above includes the request packet. As per the log, the driver is trying to open a DYNAMIC and OPTIMISTIC cursor for executing the select query. As of now, we don't support OPTIMISTIC, SCROLL-LOCKS and UPDATABLE cursors ([link](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/48cbd7758cd63ade67a6c2c2d3ed3d38ea073051/contrib/babelfishpg_tsql/src/cursor.c#L1485)).
I'll assume that you're calling a driver API to execute the SELECT statement that's internally sending this cursor open request. Could you please share the code snippet for executing this SELECT query?

**Comment by gaoxy2006git** [comment]
To modify the code of cursor. c and compile the generated file, which file is required?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babelfish-for-postgresql/babelfish_extensions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月17日(星期四) 下午4:55
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [babelfish-for-postgresql/babelfish_extensions] [Bug]: MSOLEDBSQL.1 Write is normal, read fails, and TCP communication message is recorded (Issue #853)





 
The log mentioned above includes the request packet. As per the log, the driver is trying to open a DYNAMIC and OPTIMISTIC cursor for executing the select query. As of now, we don't support OPTIMISTIC, SCROLL-LOCKS and UPDATABLE cursors (link).
 I'll assume that you're calling a driver API to execute the SELECT statement that's internally sending this cursor open request. Could you please share the code snippet for executing this SELECT query?

**Comment by gaoxy2006git** [comment]
Update&nbsp;babelfishpg_tsql.so&nbsp;file?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babelfish-for-postgresql/babelfish_extensions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月17日(星期四) 下午4:55
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [babelfish-for-postgresql/babelfish_extensions] [Bug]: MSOLEDBSQL.1 Write is normal, read fails, and TCP communication message is recorded (Issue #853)





 
The log mentioned above includes the request packet. As per the log, the driver is trying to open a DYNAMIC and OPTIMISTIC cursor for executing the select query. As of now, we don't support OPTIMISTIC, SCROLL-LOCKS and UPDATABLE cursors (link).
 I'll assume that you're calling a driver API to execute the SELECT statement that's internally sending this cursor open request. Could you please share the code snippet for executing this SELECT query?

**Comment by kuntalghosh** [comment]
We need the application code that's causing this failure. We would like to reproduce the scenario using the same driver at our end.
