### ISSUE TITLE
[Bug]: BABEL_2.X_DEV babelfish_extensions/contrib/babelfishpg_money to be unable to build 

### ISSUE THREAD

**Issue by liyuejin** [babelfish-for-postgresql/babelfish_extensions#878]
### What happened?

When I execute sudo make on ubuntu22.04, the compilation reports an error. I don't know how to handle it. Please check whether the program is buggy.

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_money

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Relevant log output

```shell
sudo make
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
make: --pgxs: 没有那个文件或目录
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
/bin/sh: 1: --version: not found
make: *** 没有规则可制作目标“/fixeddecimal--1.1.0_base.sql”，由“babelfishpg_money--1.1.0.sql” 需求。 停止。
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by liyuejin** [comment]
Version
IS BABEL_2_X_DEV

**Comment by suprio-amzn** [comment]
@liyuejin: Is this still a problem?
