### ISSUE TITLE
[Bug]: If used with sqlcmd 18 encryption error is returned. 17 is fine

### ISSUE THREAD

**Issue by Belorus** [babelfish-for-postgresql/babelfish_extensions#891]
### What happened?

If i run simple SELECT 1 under sqlcmd 18 i see following:

Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Encryption not supported on SQL Server..
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Client unable to establish connection.

I use following sqlcmd on alpine:
https://download.microsoft.com/download/8/6/8/868e5fc4-7bfe-494d-8f9d-115cbcdb52ae/msodbcsql18_18.1.2.1-1_amd64.apk
https://download.microsoft.com/download/8/6/8/868e5fc4-7bfe-494d-8f9d-115cbcdb52ae/mssql-tools18_18.1.1.1-1_amd64.apk

I run sqlcmd with -C flag which trusts any server certificate

### Version

2.1.1 from https://hub.docker.com/layers/jonathanpotts/babelfishpg/2.1.1/images/sha256-981aba45e0b805126a66845e72a6b5253daad65ffe1d233fc3237d3cac59cafe?context=explore

Dockerfile: https://github.com/jonathanpotts/docker-babelfishpg/blob/main/Dockerfile

### Which flavor of Linux are you using when you see the bug?

Ubuntu (Default)

### Relevant log output

```shell
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Encryption not supported on SQL Server..
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Client unable to establish connection.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by suprio-amzn** [comment]
It is true that the Version 18 of the Microsoft ODBC Driver for SQL Server comes with breaking changes:

https://techcommunity.microsoft.com/t5/sql-server-blog/odbc-driver-18-0-for-sql-server-released/ba-p/3169228

However, when I use this new ODBC version with Babelfish for Aurora PostgreSQL for both 2.1.2 and 2.2.0 releases, I am able to successfully connect to the server from the `sqlcmd` utility.

Could you review this page to see whether the server is setup correctly for encrypted connections?

https://babelfishpg.org/docs/usage/security/

**Comment by Belorus** [comment]
Thanks for quick response. I took latest 2.2.0 docker image from https://hub.docker.com/r/jonathanpotts/babelfishpg and enabled SSL in config, and it failed to start with error

`SSL is not supported by this build` 

Can it be that babelfish in image is compiled without SSL?
https://github.com/jonathanpotts/docker-babelfishpg/blob/main/Dockerfile

**Comment by Belorus** [comment]
Case solved :) Jonathan reworked image a bit to include ssl, and after few commands that generate certificate & enable SSL in config - SQL cmd works perfectly.
