### ISSUE TITLE
[Question]: Single vs. multiple instances

### ISSUE THREAD

**Issue by spencercw** [babelfish-for-postgresql/babelfish_extensions#9]
### Contact Details

@spencercw

### What's the question?

Hi. I'm a little confused about the `single-db` and `multi-db` migration modes. The [documentation](https://babelfishpg.org/docs/installation/single-multiple/) states:

> In the case of `single-db`, MS SQL databases are mapped to schemas in PostgreSQL. In the case of `multi-db`, many databases are used instead of just one.

So my expectation is that, in `single-db` mode I can create execute `create database` multiple times from a TDS connection, and that will be transparently mapped to multiple PostgreSQL schemas. However, when I try to create the second database it tells me: 'Only one user database allowed under single-db mode.'

If I try again in `multi-db` mode, I can create multiple databases, and I end up with multiple PostgreSQL schemas (which is what I want), but if I try to query across these two databases it tells me: 'Cross DB query is not supported.'

So I guess my question is:
1. What migration mode should I be using if I want SQL Server databases mapped to PostgreSQL schemas?
2. How do I make cross-database/schema queries work?

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nasbyj** [comment]
Thanks for the report; we are currently investigating this.

**Comment by robverschoor** [comment]
Single-db means that there can only be a single migrated SQL Server user database at a time. If you need more than one user database, use multi-db. The advantage of single-db is that the schema names in the original SQL Server remain unchanged in the PG database that the TDS connection is connection to (there can be only one such Babelfish PG database in a PG cluster at a time. WIth multiple user database, these are basically flattened into the Babelfish PG database, and the schema names get prefixed with the database names, i.e. when you connect to that database though the PG port, you see mydb_dbo, mydb_myschema, yourdb_dbo, yourdb_yourschema; from TDS the experience is similar to T-SQL where you do USE mydb and the you see schemas dbo and myschema (and guest, but that's not currently implemented for user databases in Babelfish).

As for cross-DB queries: 3-part object name references currently only work inside the current database. It is on the roadmap to extend this to other databases as well, to get a similar experiences as in SQL Server.
