### ISSUE TITLE
(question) How to get the pgsql sql stmt 

### ISSUE THREAD

**Issue by bfcamara** [babelfish-for-postgresql/babelfish_extensions#929]
I am in the middle of a migration of a huge SQL Server setup to AWS Aurora with Babelfish. Some complex  queries are having performance issues that we need to fix it. 

In the AWS console I can get the T-SQL original query. I thought that  using dbeaver session management tool connected to the pgsql port I would have access to the pgsql translated stmt, but in fact I still see the original T-SQL stmt there.

How can I get the pgsql stmt translated by babelfish and it is going to be executed in postgres instance?

**Comment by forestkeeper** [comment]
the translate didn't work on the sql -> sql transform
So the answer is you'll not be able to get the psql 'sql' corresponding to the original TSQL 'sql'
If there is a performance problem, there're some profiling tools to help find out where the time is consumed

you may refer to this doc : https://babelfishpg.org/docs/usage/query_planning/

**Comment by robverschoor** [comment]
To add, Babelfish does not translate T-SQL into PG. Babelfish adds the pltsql language in which SQL objects can be created, and when you reveng those you'll get T-SQL syntax in a PG-style wrapper.
