### ISSUE TITLE
[Enhancement]: Calling Stored Procedures in another database within the same Instance

### ISSUE THREAD

**Issue by cleyva2017** [babelfish-for-postgresql/babelfish_extensions#93]
### Describe how this change will improve the Babelfish website.

We are evaluating babelfish to migrate our  applications with a huge sqlserver backend, the problem is that we use a lot cross database calls. we have several databases involved, we use a database to store functions and stored procedures that are called from another storeprocedures from the other database. But when we try to call sp from the other database using , EXEC <dbname>.dbo.SP_TEST the following error shows => Msg 33557097, Level 16, State 1, Line 1
Cross DB query is not supported, the same error when we execute a sql statement like that SELECT * FROM <dbname>.dbo.TEST_TABLE. Is it planned to add this functionality and when?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
In the current v.1.1.0 and the upcoming v.1.2.0 releases, 3-part object name references are supported inside the current database only -- meaning that cross-DB queries are currently not supported indeed. 
Adding support for cross-DB object references is on the roadmap as this is an important feature to support.

**Comment by suprio-amzn** [comment]
This is currently supported. Please see https://babelfishpg.org/docs/versions/babelfish-2-2-0.html#changes.
