### ISSUE TITLE
[Question]: RPM packages

### ISSUE THREAD

**Issue by staticlibs** [babelfish-for-postgresql/babelfish_extensions#962]
### Contact Details

Alex Kasko <alex.staticlibs@gmail.com>

### What's your question?

My current employer is planning to run an existing application on Babelfish on Amazon Aurora. I was doing local builds of Babelfish to use them in test and for possible non-cloud deployments. I've been familiar with RPM packaging for Fedora (was working for Red Hat in the past) and decided to set up Babelfish RPM builds for Fedora and RHEL.

[Fedora Copr](https://docs.pagure.org/copr.copr/user_documentation.html#faq) is a public build system for community packages. I've set up [Babelfish RPM packages](https://copr.fedorainfracloud.org/coprs/wilton/babelfish-for-postgresql/) builds on Copr for Fedora and for EL 7, 8 and 9. These packages bring some QoL improvements, like systemd integration and adding TDS to preload libs. Perhaps they might be of interest to wider Babelfish community.

If it sounds like a good idea, it is possible to make these packages more "official" - if someone from [Babelfish Maintainers](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/BABEL_2_X_DEV/MAINTAINERS.md#current-maintainers) would like to create an official Copr account for Babelfish (I've used my existing account from one of my old projects), I can assist with moving the [RPM spec repos](https://github.com/wiltondb) to Babelfish GitHub org and with Copr builds setup.

On the other hand (if "official" RPMs are undesired), if necessary, I can clearly mark the existing RPMs as "unofficial" (replace in description "Babelfish packages" to "packages based on a source code from Babelfish" etc).

Notes: there are no plans to propose these packages for inclusion into Fedora itself (the nature of "modified PostgreSQL" makes this unrealistic); there are ideas to set up similar DEB packages on [Ubuntu PPA](https://launchpad.net/ubuntu/+ppas), but no immediate plans to do so.

Thanks for making this project open-source!

### Version

Initial RPMs are for 2.2.0 (intended to be updated):

 - [BABEL_2_2_0__PG_14_5](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/releases/tag/BABEL_2_2_0__PG_14_5)
 - [BABEL_2_2_0](https://github.com/babelfish-for-postgresql/babelfish_extensions/releases/tag/BABEL_2_2_0) 

### Extension

- babelfishpg-money
- babelfishpg-common
- babelfishpg-tds
- babelfishpg-tsql

### Which flavor of Linux are you using

RHEL, EL derivatives,  Fedora.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by staticlibs** [comment]
I now build RPMs from modified sources, I've renamed the package from `babelfishpg` to `wiltondb` to clearly show that it is not official and moved it to [this Copr project](https://copr.fedorainfracloud.org/coprs/wiltondb/wiltondb). I'll close this issue for now. If the idea of having official Copr builds for upstream Babelfish will ever be desired - I can happily contribute spec files for that.

**Comment by robverschoor** [comment]
Why was it called WiltonDB ? Just asking.

**Comment by staticlibs** [comment]
Apologies if I am misinterpreting the question, answering "why is it not called Babelfish?":

Main version is Windows one, I cannot call it "Babelfish for Windows", because Babelfish officially [does not support Windows](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/263#issuecomment-1501179255). Babelfish codebase relies on a number of assumptions about the toolchain (for example: 128-bit integer support, variable-length struct fields, extern variables visibility) that are incompatible with MSVC compiler. Windows porting patches applied to Babelfish are numerous and not trivial, if WiltonDB misbehaves or crashes when running on Windows ([example of such crash](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/1581)), it does not necessary mean that Babelfish running on Linux will have the same problem. Linux packages are supplementary and are built from the same modified sources as Windows one, so also named WiltonDB to clearly show that these packages are not "vanilla Babelfish" (like [docker-babelfishpg](https://github.com/jonathanpotts/docker-babelfishpg)), for example [this patch](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/1933) is included (because it is important for PyODBC usage) that is currently not present in any released Babelfish version. The name itself does not have any intrinsic meaning - just a geographical name.

**Comment by robverschoor** [comment]
Thanks, I was just curious. Is that Wilton, Salisbury, UK ?

**Comment by staticlibs** [comment]
It is initially named after the Wilton street in central London, overall it is a [relatively popular](https://en.wikipedia.org/wiki/Wilton) geographical name.

**Comment by robverschoor** [comment]
Curiosity satisfied.
