### ISSUE TITLE
SQL Server's 'Select FOR JSON PATH'

### ISSUE THREAD

**Issue by ssword62** [babelfish-for-postgresql/babelfish_extensions#987]
On Oct 9, 2022 there was a comment that this feature **SQL Server's 'Select FOR JSON PATH'** is on your roadmap.
I'm trying to test our app with babelfish and I'm currently stuck on this feature.
Any tentative date when will this be implemented?
Thanks.

**Comment by robverschoor** [comment]
It'll be in the next Babelfish release, v.2.3.0.
